export const accessories = [
  "Meginord's Girdle",
  "Gloomfang",
  "Ungil's Harmony",
  "Doedre's Damning",
  "Marylene's Fallacy",
  "Malachai's Artifice",
  "Andvarius",
  "Blackheart",
  "Perandus Signet",
  "Bated Breath",
  "Lori's Lantern",
  "Daresso's Salute",
  "Immortal Flesh",
  "Rashkaldor's Patience",
  "Thief's Torment",
  "Essence Worm",
  "Heartbound Loop",
  "Headhunter",
  "Precursor's Emblem",
  "Sibyl's Lament",
  "Ming's Heart",
  "Maligaro's Cruelty",
  "Tavukai",
  "Shaper's Seed",
  "Le Heup of All",
  "Stormfire",
  "Araku Tiki",
  "Darkness Enthroned",
  "The Anvil",
  "The Halcyon",
  "The Taming",
  "Ventor's Gamble",
  "Circle of Guilt",
  "Voll's Devotion",
  "String of Servitude",
  "Perandus Blazon",
  "Karui Charge",
  "Sacrificial Heart",
  "Timeclasp",
  "Dream Fragments",
  "Warped Timepiece",
  "Profane Proxy",
  "The Pandemonius",
  "Siegebreaker",
  "Leash of Oblation",
  "Karui Ward",
  "The Nomad",
  "Yoke of Suffering",
  "Tear of Purity",
  "Faminebind",
  "Mark of the Shaper",
  "Atziri's Foible",
  "Ngamahu Tiki",
  "Doryani's Invitation",
  "The Retch",
  "The Aylardex",
  "The Ignomon",
  "Stone of Lazhwar",
  "Kikazaru",
  "Death Rush",
  "Bisco's Collar",
  "Bloodboil",
  "Prismweave",
  "Pyre",
  "Belt of the Deceiver",
  "Wurm's Molt",
  "Retaliation Charm",
  "Circle of Anguish",
  "Circle of Regret",
  "The Ascetic",
  "Rigwald's Curse",
  "Badge of the Brotherhood",
  "Ascent From Flesh",
  "Aul's Uprising",
  "Carnage Heart",
  "Victario's Acuity",
  "Circle of Fear",
  "The Pariah",
  "Xoph's Blood",
  "Romira's Banquet",
  "The Flow Untethered",
  "Berek's Pass",
  "Sidhebreath",
  "Berek's Grip",
  "Ryslatha's Coil",
  "Praxis",
  "The Jinxed Juju",
  "Vivinsect",
  "Snakepit",
  "The Hungry Loop",
  "Mokou's Embrace",
  "Sunblast",
  "Astramentis",
  "Eye of Chayula",
  "Fury Valve",
  "Kaom's Way",
  "Circle of Nostalgia",
  "Willowgift",
  "Hyrri's Truth",
  "Kaom's Sign",
  "Impresence",
  "Putembo's Valley",
  "Bisco's Leash",
  "Choir of the Storm",
  "Ahkeli's Valley",
  "Gluttony",
  "Coward's Legacy",
  "Perquil's Toe",
  "Voideye",
  "Bloodgrip",
  "Winterheart",
  "Voidheart",
  "Dyadian Dawn",
  "Mark of the Elder",
  "Soul Tether",
  "Cyclopean Coil",
  "Blood of Corruption",
  "Solstice Vigil",
  "The Warden's Brand",
  "Maligaro's Restraint",
  "Icefang Orbit",
  "The Magnate",
  "Timetwist",
  "Shavronne's Revelation",
  "Star of Wraeclast",
  "Presence of Chayula",
  "Call of the Brotherhood",
  "The Primordial Chain",
  "Coward's Chains",
  "Putembo's Meadow",
  "Gifts from Above",
  "The Torrent's Reclamation",
  "Storm Secret",
  "Night's Hold",
  "Umbilicus Immortalis",
  "Uzaza's Mountain",
  "Venopuncture",
  "Mutewind Seal",
  "Extractor Mentis",
  "Brinerot Mark",
  "The Effigon",
  "Soulthirst",
  "Ahkeli's Meadow",
  "Rigwald's Crest",
  "Perseverance",
  "Xoph's Heart",
  "Mark of Submission",
  "Berek's Respite",
  "Feastbind",
  "Emberwake",
  "Hinekora's Sight",
  "Ngamahu's Sign",
  "Astral Projector",
  "Mother's Embrace",
  "Tasalio's Sign",
  "Uzaza's Valley",
  "Eyes of the Greatwolf",
  "Demigod's Eye",
  "Voice of the Storm",
  "Valyrium",
  "Redblade Band",
  "Hyperboreus",
  "The Tactician",
  "Natural Hierarchy",
  "Uzaza's Meadow",
  "Putembo's Mountain",
  "Blightwell",
  "Ahkeli's Mountain",
  "Auxium",
  "Demigod's Bounty",
  "Valako's Sign",
  "Eye of Innocence",
  "Bear's Girdle",
  "The Felbog Fang",
  "Winterweave",
  "Warrior's Legacy",
  "Zerphi's Heart",
  "Pyroshock Clasp",
  "The Ephemeral Bond",
  "The Highwayman",
  "The Druggery",
  "Replica Hyrri's Truth",
  "Replica Soul Tether",
  "Replica Prismweave",
  "Replica Karui Ward",
  "Replica Headhunter",
];

export const armours = [
  "Wreath of Phrecia",
  "Rainbowstride",
  "The Peregrine",
  "Emperor's Vigilance",
  "The Fracturing Spinner",
  "Darkray Vectors",
  "The Vertex",
  "Fractal Thoughts",
  "Ezomyte Peak",
  "Abyssus",
  "Great Old One's Tentacles",
  "Crown of the Inward Eye",
  "Wraithlord",
  "Mark of the Red Covenant",
  "Snakebite",
  "Asphyxia's Wrath",
  "Tabula Rasa",
  "Veruso's Battering Rams",
  "Rat's Nest",
  "The Formless Flame",
  "Steppan Eard",
  "Lochtonial Caress",
  "Alpha's Howl",
  "The Baron",
  "Demon Stitcher",
  "Esh's Visage",
  "Shadows and Dust",
  "Atziri's Acuity",
  "Shavronne's Wrappings",
  "Farrul's Fur",
  "Frostferno",
  "Queen of the Forest",
  "Gorgon's Gaze",
  "Vix Lunaris",
  "Surgebinders",
  "Bronn's Lithe",
  "Kaom's Heart",
  "Tombfist",
  "Soul Strike",
  "Wildwrap",
  "Facebreaker",
  "The Surrender",
  "Geofri's Sanctuary",
  "Command of the Pit",
  "Incandescent Heart",
  "Cospri's Will",
  "Carcass Jack",
  "Bubonic Trail",
  "Farrul's Fur",
  "Starkonja's Head",
  "Skin of the Lords",
  "Matua Tupuna",
  "Great Old One's Ward",
  "Asenath's Mark",
  "Hrimnor's Resolve",
  "The Eternal Apple",
  "Scold's Bridle",
  "The Embalmer",
  "Inpulsa's Broken Heart",
  "Shaper's Touch",
  "Painseeker",
  "Sadima's Touch",
  "Kalisa's Grace",
  "Abberath's Hooves",
  "Offering to the Serpent",
  "Kongming's Stratagem",
  "Wyrmsign",
  "Skirmish",
  "Ambu's Charge",
  "Geofri's Crest",
  "Soul Mantle",
  "Kingsguard",
  "Cherrubim's Maleficence",
  "Brinerot Whalers",
  "Wanderlust",
  "The Eternity Shroud",
  "Windshriek",
  "Thundersight",
  "The Covenant",
  "Lightpoacher",
  "Volkuur's Guidance",
  "Eber's Unification",
  "Sunspite",
  "Crystal Vault",
  "Memory Vault",
  "Gang's Momentum",
  "Stormcharger",
  "Ralakesh's Impatience",
  "Atziri's Splendour",
  "Loreweave",
  "Soul Mantle",
  "The Unshattered Will",
  "Honourhome",
  "Giantsbane",
  "Wondertrap",
  "Daresso's Defiance",
  "The Three Dragons",
  "Deerstalker",
  "Rime Gaze",
  "Kingsguard",
  "Three-step Assault",
  "Lioneye's Paws",
  "Beacon of Madness",
  "Saqawal's Talons",
  "Fenumus' Spinnerets",
  "Nomic's Storm",
  "Alberon's Warpath",
  "The Blood Dance",
  "Craiceann's Tracks",
  "Dance of the Offered",
  "Greedtrap",
  "Victario's Flight",
  "Atziri's Step",
  "Redblade Tramplers",
  "The Infinite Pursuit",
  "Shavronne's Gambit",
  "Kaom's Roots",
  "Goldwyrm",
  "The Stampede",
  "Sin Trek",
  "Voidwalker",
  "Duskblight",
  "Torchoak Step",
  "Mutewind Whispersteps",
  "Bones of Ullr",
  "Yriel's Fostering",
  "Devoto's Devotion",
  "Mask of the Tribunal",
  "Craiceann's Pincers",
  "Flesh and Spirit",
  "Hrimsorrow",
  "The Gull",
  "Southbound",
  "Saqawal's Winds",
  "Shackles of the Wretched",
  "Storm's Gift",
  "Drillneck",
  "Maloney's Nightfall",
  "Aurseize",
  "Doedre's Tenure",
  "Infernal Mantle",
  "Haemophilia",
  "Victario's Influence",
  "Blasphemer's Grasp",
  "Carcass Jack",
  "Skyforth",
  "Tinkerskin",
  "Tinkerskin",
  "Curtain Call",
  "The Devouring Diadem",
  "Hands of the High Templar",
  "Voidfletcher",
  "Sundance",
  "Slitherpinch",
  "Dendrobate",
  "Skullhead",
  "Thousand Teeth Temu",
  "Lioneye's Vision",
  "Saffell's Frame",
  "Hale Negator",
  "Shroud of the Lightless",
  "The Deep One's Hide",
  "Bronn's Lithe",
  "Vis Mortis",
  "Daresso's Defiance",
  "The Covenant",
  "The Coming Calamity",
  "Hyrri's Ire",
  "Soul Mantle",
  "Fleshcrafter",
  "Gruthkul's Pelt",
  "Atziri's Splendour",
  "Dendrobate",
  "Belly of the Beast",
  "The Beast Fur Shawl",
  "Victario's Influence",
  "The Brass Dome",
  "Lioneye's Vision",
  "Cherrubim's Maleficence",
  "The Ivory Tower",
  "Sporeguard",
  "Cloak of Defiance",
  "Craiceann's Carapace",
  "Maloney's Mechanism",
  "The Tempest's Binding",
  "Assailum",
  "Whakatutuki o Matua",
  "Triad Grip",
  "Iron Heart",
  "Oskarm",
  "Sentari's Answer",
  "Jaws of Agony",
  "Blackgleam",
  "The Anticipation",
  "Saqawal's Flock",
  "Bitterbind Point",
  "Death's Oath",
  "Worldcarver",
  "Light of Lunaris",
  "Vixen's Entrapment",
  "Seven-League Step",
  "Malachai's Simula",
  "Atziri's Mirror",
  "Crown of Thorns",
  "Hyrri's Bite",
  "Malachai's Loop",
  "Shavronne's Pace",
  "Veil of the Night",
  "The Restless Ward",
  "Thunderfist",
  "Maligaro's Lens",
  "Doedre's Scorn",
  "Lightning Coil",
  "Crown of Eyes",
  "Doedre's Skin",
  "Lightbane Raiment",
  "Chernobog's Pillar",
  "Loreweave",
  "Prism Guardian",
  "Heretic's Veil",
  "Maligaro's Virtuosity",
  "Empire's Grasp",
  "Black Sun Crest",
  "Voidbringer",
  "The Brine Crown",
  "The Ivory Tower",
  "The Queen's Hunger",
  "The Broken Crown",
  "Yriel's Fostering",
  "Thousand Ribbons",
  "Victario's Charity",
  "Heatshiver",
  "Ondar's Clasp",
  "Perepiteia",
  "Craiceann's Chitin",
  "Perfidy",
  "Manastorm",
  "Aegis Aurora",
  "Invictus Solaris",
  "Dialla's Malefaction",
  "Icetomb",
  "Vaal Caress",
  "Loreweave",
  "March of the Legion",
  "Maw of Conquest",
  "Solaris Lorica",
  "Windscream",
  "Magna Eclipsis",
  "Rise of the Phoenix",
  "Esh's Mirror",
  "Fox's Fortune",
  "Kaltensoul",
  "Geofri's Legacy",
  "Craghead",
  "Thirst for Horrors",
  "Deidbellow",
  "Hyrri's Demise",
  "Cragfall",
  "Lioneye's Remorse",
  "Doedre's Malevolence",
  "Malachai's Mark",
  "Asenath's Gentle Touch",
  "The Bringer of Rain",
  "Eye of Malice",
  "The Red Trail",
  "Chains of Command",
  "Yriel's Fostering",
  "Foxshade",
  "Mask of the Spirit Drinker",
  "The Brass Dome",
  "Farrul's Chase",
  "Belly of the Beast",
  "Doryani's Delusion",
  "Null and Void",
  "Ahn's Heritage",
  "Fenumus' Toxins",
  "Fenumus' Shroud",
  "Allelopathy",
  "Meginord's Vise",
  "Wheel of the Stormsail",
  "Grip of the Council",
  "Saqawal's Nest",
  "Zahndethus' Cassock",
  "Cowl of the Thermophile",
  "Cowl of the Ceraunophile",
  "Unyielding Flame",
  "Vis Mortis",
  "Scorpion's Call",
  "Wake of Destruction",
  "Redblade Banner",
  "Deidbell",
  "Breathstealer",
  "Lycosidae",
  "Wall of Brambles",
  "Leper's Alms",
  "Martyr's Crown",
  "Rathpith Globe",
  "Goldrim",
  "The Formless Inferno",
  "Dendrobate",
  "Icetomb",
  "Rigwald's Quills",
  "Rotting Legion",
  "Voll's Protector",
  "The Shattered Divinity",
  "The Tempest's Liberation",
  "Obscurantis",
  "Cloak of Flame",
  "The Rat Cage",
  "The Restless Ward",
  "Doryani's Fist",
  "Winds of Change",
  "Voll's Vision",
  "Brinerot Flag",
  "Trolltimber Spire",
  "Icetomb",
  "The Snowblind Grace",
  "Indigon",
  "Chalice of Horrors",
  "Flamesight",
  "Saemus' Gift",
  "Fairgraves' Tricorne",
  "Leer Cast",
  "Galesight",
  "Kaltenhalt",
  "Ashrend",
  "Tukohama's Fortress",
  "Skin of the Loyal",
  "Inya's Epiphany",
  "The Queen's Hunger",
  "Bloodbond",
  "Dusktoe",
  "Geofri's Sanctuary",
  "Zeel's Amplifier",
  "Cloak of Defiance",
  "Perfidy",
  "Briskwrap",
  "Algor Mortis",
  "Solaris Lorica",
  "The Iron Fortress",
  "Bronn's Lithe",
  "Lightning Coil",
  "Infernal Mantle",
  "The Restless Ward",
  "Mistwall",
  "Atziri's Reflection",
  "Infernal Mantle",
  "Speaker's Wreath",
  "Kintsugi",
  "Doedre's Skin",
  "Shavronne's Wrappings",
  "Bloodbond",
  "Cloak of Tawm'r Isley",
  "The Signal Fire",
  "Repentance",
  "Zahndethus' Cassock",
  "Chains of Command",
  "Incandescent Heart",
  "Chains of Command",
  "Doedre's Skin",
  "Cherrubim's Maleficence",
  "Kingsguard",
  "The Covenant",
  "Bloodbond",
  "Fenumus' Shroud",
  "Fenumus' Weave",
  "Daresso's Courage",
  "Ashrend",
  "Queen of the Forest",
  "The Coming Calamity",
  "Mind of the Council",
  "Apep's Supremacy",
  "Springleaf",
  "Mindspiral",
  "Broken Faith",
  "Mutewind Pennant",
  "Bramblejack",
  "Inpulsa's Broken Heart",
  "The Perfect Form",
  "Greed's Embrace",
  "Omeyocan",
  "Greed's Embrace",
  "Aukuna's Will",
  "Farrul's Fur",
  "Asenath's Chant",
  "Cospri's Will",
  "Doryani's Prototype",
  "Demigod's Beacon",
  "Demigod's Dominance",
  "Crest of Perandus",
  "Garb of the Ephemeral",
  "Dialla's Malefaction",
  "Fleshcrafter",
  "Glitterdisc",
  "Ambu's Charge",
  "Farrul's Pounce",
  "Cowl of the Cryophile",
  "Crown of the Tyrant",
  "Titucius' Span",
  "Crown of the Pale King",
  "Farrul's Bite",
  "The Queen's Hunger",
  "Saqawal's Nest",
  "Shadowstitch",
  "The Rat Cage",
  "Garb of the Ephemeral",
  "Mask of the Stitched Demon",
  "Malachai's Vision",
  "Dialla's Malefaction",
  "Cloak of Flame",
  "Ahn's Contempt",
  "Apep's Slumber",
  "Fox's Fortune",
  "Wall of Brambles",
  "Atziri's Splendour",
  "Chitus' Apex",
  "Hrimburn",
  "Death's Oath",
  "The Perfect Form",
  "Greed's Embrace",
  "Thousand Ribbons",
  "Victario's Influence",
  "Kitava's Thirst",
  "Foxshade",
  "Lightning Coil",
  "The Beast Fur Shawl",
  "Malachai's Awakening",
  "Foxshade",
  "Ambu's Charge",
  "Craiceann's Carapace",
  "Briskwrap",
  "Daresso's Defiance",
  "Death's Door",
  "Demigod's Triumph",
  "Rearguard",
  "Architect's Hand",
  "Garukhan's Flight",
  "Fox's Fortune",
  "The Perfect Form",
  "Ezomyte Hold",
  "Machina Mitts",
  "Rotting Legion",
  "Death's Oath",
  "Kintsugi",
  "Rotting Legion",
  "Ylfeban's Trickery",
  "Bramblejack",
  "Perfidy",
  "The Iron Fortress",
  "Wildwrap",
  "Deshret's Vise",
  "Wall of Brambles",
  "Crystal Vault",
  "The Oak",
  "Voll's Protector",
  "Iron Heart",
  "The Eternity Shroud",
  "Plume of Pursuit",
  "Viper's Scales",
  "Slavedriver's Hand",
  "Solaris Lorica",
  "Broadstroke",
  "The Iron Fortress",
  "Lightbane Raiment",
  "Ashrend",
  "Iron Heart",
  "Gruthkul's Pelt",
  "Garb of the Ephemeral",
  "Doryani's Prototype",
  "Briskwrap",
  "Forbidden Shako",
  "Abhorrent Interrogation",
  "The Immortal Will",
  "Willclash",
  "The Ghastly Theatre",
  "Mercenary's Lot",
  "Crest of Desire",
  "Blunderbore",
  "Expedition's End",
  "Replica Grip of the Council",
  "Replica Perfect Form",
  "Replica Alberon's Warpath",
  "Replica Inya's Epiphany",
  "Replica Eternity Shroud",
  "Replica Atziri's Acuity",
  "Replica Red Trail",
  "Replica Maloney's Mechanism",
  "Replica Ambu's Charge",
  "Replica Voidwalker",
  "Replica Kaom's Heart",
  "Replica Mistwall",
  "Replica Bones of Ullr",
  "Replica Farrul's Fur",
  "Replica Shroud of the Lightless",
  "Maw of Mischief",
  "The Fledgling",
  "Corpsewalker",
];

export const weapons = [
  "Abberath's Horn",
  "Actum",
  "Advancing Fortress",
  "Agnerod",
  "Agnerod East",
  "Agnerod North",
  "Agnerod South",
  "Agnerod West",
  "Ahn's Might",
  "Al Dhih",
  "Allure",
  "Amplification Rod",
  "Apep's Rage",
  "Arakaali's Fang",
  "Arborix",
  "Ashcaller",
  "Ashes of the Sun",
  "Atziri's Disfavour",
  "Augyre",
  "Aurumvorax",
  "Axiom Perpetuum",
  "Balefire",
  "Beltimber Blade",
  "Bino's Kitchen Knife",
  "Bitterdream",
  "Blood of Summer",
  "Bloodplay",
  "Bloodseeker",
  "Brain Rattler",
  "Breath of the Council",
  "Brightbeak",
  "Brutus' Lead Sprinkler",
  "Callinellus Malleus",
  "Cameria's Avarice",
  "Cameria's Maul",
  "Cane of Unravelling",
  "Cerberus Limb",
  "Chaber Cairn",
  "Chin Sol",
  "Chitus' Needle",
  "Chober Chaber",
  "Clayshaper",
  "Cold Iron Point",
  "Corona Solaris",
  "Cospri's Malice",
  "Cybil's Paw",
  "Daresso's Passion",
  "Darkscorn",
  "Death's Hand",
  "Death's Harp",
  "Death's Opus",
  "Debeon's Dirge",
  "Demigod's Authority",
  "Disintegrator",
  "Divinarius",
  "Doomfletch",
  "Doomfletch's Prism",
  "Doomsower",
  "Doon Cuebiyari",
  "Doryani's Catalyst",
  "Dreadarc",
  "Dreadbeak",
  "Dreadsurge",
  "Dreamfeather",
  "Duskdawn",
  "Dyadus",
  "Dying Breath",
  "Dying Breath",
  "Earendel's Embrace",
  "Eclipse Solaris",
  "Edge of Madness",
  "Ephemeral Edge",
  "Essentia Sanguis",
  "Essentia Sanguis",
  "Ewar's Mirage",
  "Fate of the Vaal",
  "Femurs of the Saints",
  "Fencoil",
  "Fidelitas' Spike",
  "Flesh-Eater",
  "Fragment of Eternity",
  "Frostbreath",
  "Geofri's Baptism",
  "Geofri's Devotion",
  "Gorebreaker",
  "Goredrill",
  "Grelwood Shank",
  "Hand of Thought and Motion",
  "Hand of Wisdom and Action",
  "Heartbreaker",
  "Hegemony's Era",
  "Hezmana's Bloodlust",
  "Hiltless",
  "Hopeshredder",
  "Hrimnor's Dirge",
  "Hrimnor's Hymn",
  "Hyaon's Fury",
  "Ichimonji",
  "Infractem",
  "Innsbury Edge",
  "Iron Commander",
  "Izaro's Dilemma",
  "Jack, the Axe",
  "Jorrhast's Blacksteel",
  "Kaom's Primacy",
  "Kingmaker",
  "Kitava's Feast",
  "Kondo's Pride",
  "Kongor's Undying Rage",
  "Lakishu's Blade",
  "Last Resort",
  "Lavianga's Wisdom",
  "Law of the Wilds",
  "Lifesprig",
  "Limbsplit",
  "Lioneye's Glare",
  "Mark of the Doubting Knight",
  "Marohi Erqi",
  "Martyr of Innocence",
  "Midnight Bargain",
  "Mightflay",
  "Mirebough",
  "Mjölner",
  "Mon'tregul's Grasp",
  "Moonbender's Wing",
  "Moonsorrow",
  "Mortem Morsu",
  "Nebulis",
  "Nebuloch",
  "Ngamahu's Flame",
  "Null's Inclination",
  "Nuro's Harp",
  "Nycta's Lantern",
  "Obliteration",
  "Oni-Goroshi",
  "Ornament of the East",
  "Oro's Sacrifice",
  "Panquetzaliztli",
  "Paradoxica",
  "Pillar of the Caged God",
  "Pillar of the Caged God",
  "Piscator's Vigil",
  "Pledge of Hands",
  "Prismatic Eclipse",
  "Quecholli",
  "Queen's Decree",
  "Queen's Escape",
  "Quill Rain",
  "Razor of the Seventh Sun",
  "Reach of the Council",
  "Realm Ender",
  "Realmshaper",
  "Reaper's Pursuit",
  "Rebuke of the Vaal",
  "Redbeak",
  "Reefbane",
  "Relentless Fury",
  "Relic of the Cycle",
  "Replica Advancing Fortress",
  "Replica Allure",
  "Replica Bitterdream",
  "Replica Bloodplay",
  "Replica Blood Thorn",
  "Replica Cold Iron Point",
  "Replica Dreamfeather",
  "Replica Duskdawn",
  "Replica Earendel's Embrace",
  "Replica Fencoil",
  "Replica Frostbreath",
  "Replica Harvest",
  "Replica Heartbreaker",
  "Replica Infractem",
  "Replica Innsbury Edge",
  "Replica Iron Commander",
  "Replica Kongor's Undying Rage",
  "Replica Last Resort",
  "Replica Midnight Bargain",
  "Replica Nebulis",
  "Replica Oro's Sacrifice",
  "Replica Paradoxica",
  "Replica Quill Rain",
  "Replica Soul Taker",
  "Replica Tempestuous Steel",
  "Replica Trypanon",
  "Replica Tulfall",
  "Replica Twyzel",
  "Replica Ungil's Gauche",
  "Replica Windripper",
  "Replica Wings of Entropy",
  "Reverberation Rod",
  "Rigwald's Charge",
  "Rigwald's Command",
  "Rigwald's Savagery",
  "Rive",
  "Roth's Reach",
  "Rust of Winter",
  "Sanguine Gambol",
  "Scaeva",
  "Scar of Fate",
  "Severed in Sleep",
  "Shade of Solaris",
  "Shimmeron",
  "Shiversting",
  "Sign of the Sin Eater",
  "Silverbough",
  "Silverbranch",
  "Singularity",
  "Sinvicta's Mettle",
  "Sire of Shards",
  "Slivertongue",
  "Song of the Sirens",
  "Soul Taker",
  "Soulwrest",
  "Spine of the First Claimant",
  "Splinter of the Moon",
  "Starforge",
  "Storm Cloud",
  "Storm Prison",
  "Story of the Vaal",
  "Taproot",
  "Taryn's Shiver",
  "Terminus Est",
  "The Black Cane",
  "The Blood Reaper",
  "The Blood Thorn",
  "The Cauteriser",
  "The Consuming Dark",
  "The Crimson Storm",
  "The Dancing Dervish",
  "The Dancing Duo",
  "The Dark Seer",
  "The Enmity Divine",
  "The Fulcrum",
  "The Goddess Bound",
  "The Goddess Scorned",
  "The Goddess Unleashed",
  "The Grey Spire",
  "The Gryphon",
  "The Harvest",
  "The Hidden Blade",
  "The Iron Mass",
  "The Poet's Pen",
  "The Princess",
  "The Rippling Thoughts",
  "The Saviour",
  "The Scourge",
  "The Screaming Eagle",
  "The Searing Touch",
  "The Searing Touch",
  "The Stormheart",
  "The Stormwall",
  "The Supreme Truth",
  "The Surging Thoughts",
  "The Tempest",
  "The Tempestuous Steel",
  "The Wasp Nest",
  "The Whispering Ice",
  "The Yielding Mortality",
  "Thunder of the Dawn",
  "Tidebreaker",
  "Tipua Kaikohuru",
  "Touch of Anguish",
  "Tremor Rod",
  "Trypanon",
  "Tulborn",
  "Tulfall",
  "Twyzel",
  "Ungil's Gauche",
  "United in Dream",
  "Uul-Netol's Embrace",
  "Uul-Netol's Kiss",
  "Varunastra",
  "Vestige of Divinity",
  "Void Battery",
  "Voidforge",
  "Voidhome",
  "Voltaxic Rift",
  "Vulconus",
  "White Wind",
  "Wideswing",
  "Widowmaker",
  "Wildslash",
  "Windripper",
  "Wings of Entropy",
  "Wings of Entropy",
  "Witchhunter's Judgment",
  "Xirgil's Crank",
  "Xoph's Inception",
  "Xoph's Nurture"
]
/* 

Go through each object and iterate the object on chrome console to grab all array entries

*/

export const currency = [
  "Orb of Alteration",
  "Orb of Fusing",
  "Orb of Alchemy",
  "Chaos Orb",
  "Gemcutter's Prism",
  "Exalted Orb",
  "Chromatic Orb",
  "Jeweller's Orb",
  "Engineer's Orb",
  "Infused Engineer's Orb",
  "Orb of Chance",
  "Cartographer's Chisel",
  "Orb of Scouring",
  "Blessed Orb",
  "Orb of Regret",
  "Regal Orb",
  "Divine Orb",
  "Vaal Orb",
  "Orb of Annulment",
  "Orb of Binding",
  "Ancient Orb",
  "Orb of Horizons",
  "Harbinger's Orb",
  "Scroll of Wisdom",
  "Portal Scroll",
  "Armourer's Scrap",
  "Blacksmith's Whetstone",
  "Glassblower's Bauble",
  "Orb of Transmutation",
  "Orb of Augmentation",
  "Mirror of Kalandra",
  "Eternal Orb",
  "Perandus Coin",
  "Silver Coin",
  "Crusader's Exalted Orb",
  "Redeemer's Exalted Orb",
  "Hunter's Exalted Orb",
  "Warlord's Exalted Orb",
  "Awakener's Orb",
  "Facetor's Lens",
  "Rogue's Marker",
  "Prime Regrading Lens",
  "Secondary Regrading Lens",
  "Tempering Orb",
  "Tailoring Orb",
  "Annulment Shard",
  "Mirror Shard",
  "Exalted Shard",
  "Binding Shard",
  "Horizon Shard",
  "Harbinger's Shard",
  "Engineer's Shard",
  "Ancient Shard",
  "Chaos Shard",
  "Regal Shard",
  "Simple Sextant",
  "Prime Sextant",
  "Awakened Sextant",
  "Blessing of Xoph",
  "Blessing of Tul",
  "Blessing of Esh",
  "Blessing of Uul-Netol",
  "Blessing of Chayula",
  "Splinter of Xoph",
  "Splinter of Tul",
  "Splinter of Esh",
  "Splinter of Uul-Netol",
  "Splinter of Chayula",
  "Timeless Karui Splinter",
  "Timeless Maraketh Splinter",
  "Timeless Eternal Empire Splinter",
  "Timeless Templar Splinter",
  "Timeless Vaal Splinter",
  "Simulacrum Splinter",
  "Stacked Deck",
];

export const cards = [
  "A Dab of Ink",
  "A Familiar Call",
  "A Mother's Parting Gift",
  "A Note in the Wind",
  "Abandoned Wealth",
  "Akil's Prophecy",
  "Alluring Bounty",
  "Alone in the Darkness",
  "Anarchy's Price",
  "Arrogance of the Vaal",
  "Assassin's Favour",
  "Atziri's Arsenal",
  "Audacity",
  "Azyran's Reward",
  "Baited Expectations",
  "Beauty Through Death",
  "Birth of the Three",
  "Blessing of God",
  "Blind Venture",
  "Boon of Justice",
  "Boon of the First Ones",
  "Boundless Realms",
  "Bowyer's Dream",
  "Brother's Stash",
  "Buried Treasure",
  "Burning Blood",
  "Call to the First Ones",
  "Cameria's Cut",
  "Cartographer's Delight",
  "Chaotic Disposition",
  "Council of Cats",
  "Coveted Possession",
  "Cursed Words",
  "Dark Dreams",
  "Dark Temptation",
  "Death",
  "Deathly Designs",
  "Demigod's Wager",
  "Desecrated Virtue",
  "Destined to Crumble",
  "Dialla's Subjugation",
  "Divine Justice",
  "Doedre's Madness",
  "Dying Anguish",
  "Earth Drinker",
  "Echoes of Love",
  "Emperor of Purity",
  "Emperor's Luck",
  "Etched in Blood",
  "Forbidden Power",
  "Friendship",
  "Gemcutter's Promise",
  "Gift of Asenath",
  "Gift of the Gemling Queen",
  "Glimmer of Hope",
  "Grave Knowledge",
  "Harmony of Souls",
  "Her Mask",
  "Heterochromia",
  "Hope",
  "House of Mirrors",
  "Hubris",
  "Humility",
  "Hunter's Resolve",
  "Hunter's Reward",
  "Immortal Resolve",
  "Imperial Legacy",
  "Jack in the Box",
  "Lantador's Lost Love",
  "Last Hope",
  "Left to Fate",
  "Light and Truth",
  "Lingering Remnants",
  "Lost Worlds",
  "Loyalty",
  "Luck of the Vaal",
  "Lucky Connections",
  "Lucky Deck",
  "Lysah's Respite",
  "Mawr Blaidd",
  "Merciless Armament",
  "Might is Right",
  "Mitts",
  "Monochrome",
  "More is Never Enough",
  "No Traces",
  "Nook's Crown",
  "Peaceful Moments",
  "Perfection",
  "Pride Before the Fall",
  "Pride of the First Ones",
  "Prometheus' Armoury",
  "Prosperity",
  "Rain of Chaos",
  "Rain Tempter",
  "Rats",
  "Rebirth",
  "Remembrance",
  "Sambodhi's Vow",
  "Scholar of the Seas",
  "Seven Years Bad Luck",
  "Shard of Fate",
  "Squandered Prosperity",
  "Struck by Lightning",
  "Succor of the Sinless",
  "The Academic",
  "The Admirer",
  "The Aesthete",
  "The Archmage's Right Hand",
  "The Arena Champion",
  "The Army of Blood",
  "The Artist",
  "The Avenger",
  "The Awakened",
  "The Bargain",
  "The Battle Born",
  "The Beast",
  "The Betrayal",
  "The Bitter Blossom",
  "The Blazing Fire",
  "The Body",
  "The Bones",
  "The Breach",
  "The Brittle Emperor",
  "The Cache",
  "The Cacophony",
  "The Calling",
  "The Carrion Crow",
  "The Cartographer",
  "The Cataclysm",
  "The Catalyst",
  "The Celestial Justicar",
  "The Celestial Stone",
  "The Chains that Bind",
  "The Cheater",
  "The Chosen",
  "The Coming Storm",
  "The Conduit",
  "The Craving",
  "The Cursed King",
  "The Damned",
  "The Dapper Prodigy",
  "The Dark Mage",
  "The Darkest Dream",
  "The Deal",
  "The Deceiver",
  "The Deep Ones",
  "The Demon",
  "The Demoness",
  "The Devastator",
  "The Doctor",
  "The Doppelganger",
  "The Dragon",
  "The Dragon's Heart",
  "The Dreamer",
  "The Dreamland",
  "The Drunken Aristocrat",
  "The Easy Stroll",
  "The Eldritch Decay",
  "The Encroaching Darkness",
  "The Endless Darkness",
  "The Endurance",
  "The Enlightened",
  "The Escape",
  "The Ethereal",
  "The Explorer",
  "The Eye of Terror",
  "The Eye of the Dragon",
  "The Fathomless Depths",
  "The Feast",
  "The Fiend",
  "The Fishmonger",
  "The Fletcher",
  "The Flora's Gift",
  "The Fool",
  "The Formless Sea",
  "The Forsaken",
  "The Fox",
  "The Gambler",
  "The Garish Power",
  "The Gemcutter",
  "The Gentleman",
  "The Gladiator",
  "The Golden Era",
  "The Greatest Intentions",
  "The Gulf",
  "The Hale Heart",
  "The Harvester",
  "The Hermit",
  "The Heroic Shot",
  "The Hive of Knowledge",
  "The Hoarder",
  "The Hunger",
  "The Immortal",
  "The Incantation",
  "The Innocent",
  "The Inoculated",
  "The Insatiable",
  "The Inventor",
  "The Iron Bard",
  "The Jester",
  "The Jeweller's Boon",
  "The Journalist",
  "The Journey",
  "The King's Blade",
  "The King's Heart",
  "The Landing",
  "The Last One Standing",
  "The Lich",
  "The Life Thief",
  "The Lion",
  "The Long Con",
  "The Lord in Black",
  "The Lord of Celebration",
  "The Lover",
  "The Lunaris Priestess",
  "The Mad King",
  "The Master",
  "The Master Artisan",
  "The Mayor",
  "The Mercenary",
  "The Messenger",
  "The Metalsmith's Gift",
  "The Mountain",
  "The Nurse",
  "The Oath",
  "The Obscured",
  "The Offering",
  "The Old Man",
  "The One With All",
  "The Opulent",
  "The Pack Leader",
  "The Pact",
  "The Penitent",
  "The Poet",
  "The Polymath",
  "The Porcupine",
  "The Price of Loyalty",
  "The Price of Protection",
  "The Primordial",
  "The Professor",
  "The Progeny of Lunaris",
  "The Puzzle",
  "The Queen",
  "The Rabid Rhoa",
  "The Realm",
  "The Risk",
  "The Rite of Elements",
  "The Road to Power",
  "The Ruthless Ceinture",
  "The Sacrifice",
  "The Saint's Treasure",
  "The Samurai's Eye",
  "The Scarred Meadow",
  "The Scavenger",
  "The Scholar",
  "The Seeker",
  "The Sephirot",
  "The Side Quest",
  "The Sigil",
  "The Siren",
  "The Skeleton",
  "The Soul",
  "The Spark and the Flame",
  "The Spoiled Prince",
  "The Standoff",
  "The Stormcaller",
  "The Strategist",
  "The Summoner",
  "The Sun",
  "The Surgeon",
  "The Surveyor",
  "The Survivalist",
  "The Sustenance",
  "The Sword King's Salute",
  "The Thaumaturgist",
  "The Throne",
  "The Tinkerer's Table",
  "The Tower",
  "The Traitor",
  "The Trial",
  "The Tumbleweed",
  "The Twilight Moon",
  "The Twins",
  "The Tyrant",
  "The Undaunted",
  "The Undisputed",
  "The Unexpected Prize",
  "The Union",
  "The Valkyrie",
  "The Valley of Steel Boxes",
  "The Vast",
  "The Visionary",
  "The Void",
  "The Warden",
  "The Warlord",
  "The Watcher",
  "The Web",
  "The White Knight",
  "The Wilted Rose",
  "The Wind",
  "The Witch",
  "The Wolf",
  "The Wolf's Legacy",
  "The Wolf's Shadow",
  "The Wolven King's Bite",
  "The Wolverine",
  "The World Eater",
  "The Wrath",
  "The Wretched",
  "Thirst for Knowledge",
  "Three Faces in the Dark",
  "Three Voices",
  "Thunderous Skies",
  "Time-Lost Relic",
  "Tranquillity",
  "Treasure Hunter",
  "Triskaidekaphobia",
  "Turn the Other Cheek",
  "Unchained",
  "Underground Forest",
  "Unrequited Love",
  "Vanity",
  "Vile Power",
  "Vinia's Token",
  "Void of the Elements",
  "Volatile Power",
  "Wealth and Power",
];

export const flasks = [
  "Atziri's Promise",
  "Blood of the Karui",
  "Bottled Faith",
  "Cinderswallow Urn",
  "Coralito's Signature",
  "Coruscating Elixir",
  "Divination Distillate",
  "Doedre's Elixir",
  "Dying Sun",
  "Forbidden Taste",
  "Kiara's Determination",
  "Lavianga's Spirit",
  "Lion's Roar",
  "Replica Lavianga's Spirit",
  "Replica Rumi's Concoction",
  "Replica Sorrow of the Divine",
  "Rotgut",
  "Rumi's Concoction",
  "Sin's Rebirth",
  "Soul Catcher",
  "Soul Ripper",
  "Taste of Hate",
  "The Overflowing Chalice",
  "The Sorrow of the Divine",
  "The Wise Oak",
  "The Writhing Jar",
  "Vessel of Vinktar",
  "Witchfire Brew",
  "Zerphi's Last Breath",
]

export const gems = [
  "Infernal Cry",
  "Ancestral Cry",
  "Ancestral Warchief",
  "Anger",
  "Animate Guardian",
  "Animate Weapon",
  "Arc",
  "Arcane Cloak",
  "Arcanist Brand",
  "Arctic Armour",
  "Creeping Frost",
  "Armageddon Brand",
  "Artillery Ballista",
  "Ball Lightning",
  "Barrage",
  "Bear Trap",
  "Berserk",
  "Blade Blast",
  "Bladefall",
  "Bladestorm",
  "Blade Vortex",
  "Blast Rain",
  "Blazing Salvo",
  "Blight",
  "Blink Arrow",
  "Blood and Sand",
  "Blood Rage",
  "Unearth",
  "Bone Offering",
  "Burning Arrow",
  "Chain Hook",
  "Blade Flurry",
  "Charged Dash",
  "Clarity",
  "Cleave",
  "Cobra Lash",
  "Purity of Ice",
  "Cold Snap",
  "Conductivity",
  "Consecrated Path",
  "Contagion",
  "Conversion Trap",
  "Convocation",
  "Cremation",
  "Bodyswap",
  "Crackling Lance",
  "Assassin's Mark",
  "Cyclone",
  "Malevolence",
  "Dark Pact",
  "Bane",
  "Dash",
  "Decoy Totem",
  "Desecrate",
  "Determination",
  "Detonate Dead",
  "Detonate Mines",
  "Devouring Totem",
  "Discharge",
  "Discipline",
  "Divine Ire",
  "Dominating Blow",
  "Double Strike",
  "Dread Banner",
  "Dual Strike",
  "Earthquake",
  "Earthshatter",
  "Elemental Hit",
  "Elemental Weakness",
  "Enduring Cry",
  "Enfeeble",
  "Ensnaring Arrow",
  "Essence Drain",
  "Ethereal Knives",
  "Explosive Arrow",
  "Fireball",
  "Scorching Ray",
  "Pyroclast Mine",
  "Purity of Fire",
  "Firestorm",
  "Fire Trap",
  "Flameblast",
  "Flame Dash",
  "Flamethrower Trap",
  "Holy Flame Totem",
  "Flame Wall",
  "Flame Surge",
  "Flammability",
  "Flesh and Stone",
  "Flesh Offering",
  "Flicker Strike",
  "Icicle Mine",
  "Freezing Pulse",
  "Frenzy",
  "Frostbite",
  "Frost Blades",
  "Frostblink",
  "Frostbolt",
  "Vortex",
  "Frost Bomb",
  "Frost Shield",
  "Frost Wall",
  "General's Cry",
  "Glacial Cascade",
  "Glacial Hammer",
  "Grace",
  "Ground Slam",
  "Haste",
  "Hatred",
  "Heavy Strike",
  "Herald of Agony",
  "Herald of Ash",
  "Herald of Ice",
  "Herald of Purity",
  "Herald of Thunder",
  "Hexblast",
  "Ice Crash",
  "Ice Nova",
  "Ice Shot",
  "Siphoning Trap",
  "Ice Spear",
  "Ice Trap",
  "Immortal Call",
  "Incinerate",
  "Infernal Blow",
  "Intimidating Cry",
  "Kinetic Blast",
  "Kinetic Bolt",
  "Lacerate",
  "Lancing Steel",
  "Leap Slam",
  "Lightning Arrow",
  "Purity of Lightning",
  "Lightning Strike",
  "Lightning Tendrils",
  "Lightning Spire Trap",
  "Lightning Trap",
  "Lightning Warp",
  "Magma Orb",
  "Ancestral Protector",
  "Mirror Arrow",
  "Molten Shell",
  "Molten Strike",
  "Vulnerability",
  "Orb of Storms",
  "Penance Brand",
  "Perforate",
  "Pestilent Strike",
  "Phase Run",
  "Seismic Trap",
  "Plague Bearer",
  "Poacher's Mark",
  "Caustic Arrow",
  "Portal",
  "Power Siphon",
  "Precision",
  "Pride",
  "Sniper's Mark",
  "Puncture",
  "Punishment",
  "Wave of Conviction",
  "Purity of Elements",
  "Rain of Arrows",
  "Raise Spectre",
  "Raise Zombie",
  "Rallying Cry",
  "Reave",
  "Brand Recall",
  "Reckoning",
  "Rejuvenation Totem",
  "Righteous Fire",
  "Riposte",
  "Purifying Flame",
  "Scourge Arrow",
  "Searing Bond",
  "Seismic Cry",
  "Shattering Steel",
  "Shield Charge",
  "Shock Nova",
  "Shockwave Totem",
  "Shrapnel Ballista",
  "Galvanic Arrow",
  "Explosive Trap",
  "Siege Ballista",
  "Sigil of Power",
  "Smite",
  "Smoke Mine",
  "Soulrend",
  "Spark",
  "Zealotry",
  "Spellslinger",
  "Spirit Offering",
  "Split Arrow",
  "Splitting Steel",
  "Static Strike",
  "Steelskin",
  "Stormbind",
  "Stormblast Mine",
  "Storm Brand",
  "Storm Burst",
  "Storm Call",
  "Summon Carrion Golem",
  "Summon Chaos Golem",
  "Summon Flame Golem",
  "Summon Ice Golem",
  "Summon Lightning Golem",
  "Summon Raging Spirit",
  "Summon Holy Relic",
  "Summon Stone Golem",
  "Summon Skeletons",
  "Summon Skitterbots",
  "Sunder",
  "Sweep",
  "Tectonic Slam",
  "Tempest Shield",
  "Temporal Chains",
  "Spectral Shield Throw",
  "Spectral Throw",
  "Tornado Shot",
  "Toxic Rain",
  "Vaal Ancestral Warchief",
  "Vaal Arc",
  "Vaal Blade Vortex",
  "Vaal Blight",
  "Vaal Burning Arrow",
  "Vaal Clarity",
  "Vaal Impurity of Ice",
  "Vaal Cold Snap",
  "Vaal Cyclone",
  "Vaal Detonate Dead",
  "Vaal Discipline",
  "Vaal Double Strike",
  "Vaal Earthquake",
  "Vaal Fireball",
  "Vaal Impurity of Fire",
  "Vaal Flameblast",
  "Vaal Glacial Hammer",
  "Vaal Grace",
  "Vaal Ground Slam",
  "Vaal Haste",
  "Vaal Ice Nova",
  "Vaal Immortal Call",
  "Vaal Impurity of Lightning",
  "Vaal Lightning Strike",
  "Vaal Lightning Trap",
  "Vaal Lightning Warp",
  "Vaal Molten Shell",
  "Vaal Breach",
  "Vaal Power Siphon",
  "Vaal Rain of Arrows",
  "Vaal Reave",
  "Vaal Righteous Fire",
  "Vaal Spark",
  "Vaal Storm Call",
  "Vaal Summon Skeletons",
  "Vaal Spectral Throw",
  "Vengeance",
  "Venom Gyre",
  "Vigilant Strike",
  "Viper Strike",
  "Vitality",
  "Void Sphere",
  "Volatile Dead",
  "Despair",
  "War Banner",
  "Warlord's Mark",
  "Whirling Blades",
  "Wild Strike",
  "Winter Orb",
  "Wintertide Brand",
  "Wither",
  "Withering Step",
  "Wrath",
  "Added Chaos Damage Support",
  "Awakened Added Chaos Damage Support",
  "Added Cold Damage Support",
  "Awakened Added Cold Damage Support",
  "Added Fire Damage Support",
  "Awakened Added Fire Damage Support",
  "Added Lightning Damage Support",
  "Awakened Added Lightning Damage Support",
  "Additional Accuracy Support",
  "Empower Support",
  "Enhance Support",
  "Enlighten Support",
  "Awakened Ancestral Call Support",
  "Arcane Surge Support",
  "Archmage Support",
  "Arrow Nova Support",
  "Awakened Arrow Nova Support",
  "Barrage Support",
  "Blasphemy Support",
  "Awakened Blasphemy Support",
  "Blind Support",
  "Block Chance Reduction Support",
  "Bloodlust Support",
  "Blood Magic Support",
  "Bonechill Support",
  "Brutality Support",
  "Awakened Brutality Support",
  "Awakened Burning Damage Support",
  "Cast On Critical Strike Support",
  "Awakened Cast On Critical Strike Support",
  "Cast when Damage Taken Support",
  "Cast on Death Support",
  "Cast on Melee Kill Support",
  "Cast when Stunned Support",
  "Cast while Channelling Support",
  "Awakened Cast While Channelling Support",
  "Chain Support",
  "Awakened Chain Support",
  "Chance to Bleed Support",
  "Chance to Flee Support",
  "Combustion Support",
  "Withering Touch Support",
  "Charged Mines Support",
  "Close Combat Support",
  "Cluster Traps Support",
  "Cold Penetration Support",
  "Awakened Cold Penetration Support",
  "Cold to Fire Support",
  "Concentrated Effect Support",
  "Controlled Destruction Support",
  "Awakened Controlled Destruction Support",
  "Culling Strike Support",
  "Hextouch Support",
  "Awakened Hextouch Support",
  "Hypothermia Support",
  "Deadly Ailments Support",
  "Awakened Deadly Ailments Support",
  "Predator Support",
  "Decay Support",
  "Efficacy Support",
  "Elemental Focus Support",
  "Awakened Elemental Focus Support",
  "Elemental Penetration Support",
  "Elemental Proliferation Support",
  "Endurance Charge on Melee Stun Support",
  "Energy Leech Support",
  "Faster Attacks Support",
  "Faster Casting Support",
  "Faster Projectiles Support",
  "Feeding Frenzy Support",
  "Fire Penetration Support",
  "Awakened Fire Penetration Support",
  "Fist of War Support",
  "Fork Support",
  "Awakened Fork Support",
  "Fortify Support",
  "Ice Bite Support",
  "Charged Traps Support",
  "Generosity Support",
  "Awakened Generosity Support",
  "Greater Multiple Projectiles Support",
  "Awakened Greater Multiple Projectiles Support",
  "Greater Volley Support",
  "Unleash Support",
  "Intensify Support",
  "High-Impact Mine Support",
  "Ignite Proliferation Support",
  "Immolate Support",
  "Impale Support",
  "Impending Doom Support",
  "Increased Area of Effect Support",
  "Awakened Increased Area of Effect Support",
  "Burning Damage Support",
  "Increased Critical Damage Support",
  "Increased Critical Strikes Support",
  "Increased Duration Support",
  "Infernal Legion Support",
  "Iron Grip Support",
  "Iron Will Support",
  "Item Quantity Support",
  "Item Rarity Support",
  "Knockback Support",
  "Lesser Multiple Projectiles Support",
  "Lesser Poison Support",
  "Life Gain on Hit Support",
  "Life Leech Support",
  "Lightning Penetration Support",
  "Awakened Lightning Penetration Support",
  "Maim Support",
  "Mana Leech Support",
  "Meat Shield Support",
  "Damage on Full Life Support",
  "Melee Physical Damage Support",
  "Awakened Melee Physical Damage Support",
  "Melee Splash Support",
  "Awakened Melee Splash Support",
  "Minefield Support",
  "Minion Damage Support",
  "Awakened Minion Damage Support",
  "Minion Life Support",
  "Minion Speed Support",
  "Mirage Archer Support",
  "Spell Echo Support",
  "Multistrike Support",
  "Awakened Multistrike Support",
  "Multiple Totems Support",
  "Multiple Traps Support",
  "Nightblade Support",
  "Onslaught Support",
  "Innervate Support",
  "Volley Support",
  "Vicious Projectiles Support",
  "Physical to Lightning Support",
  "Pierce Support",
  "Pinpoint Support",
  "Point Blank Support",
  "Poison Support",
  "Power Charge On Critical Support",
  "Pulverise Support",
  "Rage Support",
  "Ballista Totem Support",
  "Swift Affliction Support",
  "Less Duration Support",
  "Inspiration Support",
  "Blastchain Mine Support",
  "Ruthless Support",
  "Second Wind Support",
  "Shockwave Support",
  "Slower Projectiles Support",
  "Spell Cascade Support",
  "Awakened Spell Cascade Support",
  "Awakened Spell Echo Support",
  "Spell Totem Support",
  "Ancestral Call Support",
  "Infused Channelling Support",
  "Stun Support",
  "Elemental Army Support",
  "Summon Phantasm Support",
  "Awakened Swift Affliction Support",
  "Swift Assembly Support",
  "Swiftbrand Support",
  "Trap Support",
  "Trap and Mine Damage Support",
  "Advanced Traps Support",
  "Unbound Ailments Support",
  "Awakened Unbound Ailments Support",
  "Awakened Unleash Support",
  "Urgent Orders Support",
  "Awakened Vicious Projectiles Support",
  "Vile Toxins Support",
  "Void Manipulation Support",
  "Awakened Void Manipulation Support",
  "Elemental Damage with Attacks Support",
  "Awakened Elemental Damage with Attacks Support"
]

export const jewels = [
  "Anatomical Knowledge",
  "Ancient Waystones",
  "Apex Mode",
  "Apparitions",
  "To Dust",
  "Assassin's Haste",
  "Atziri's Reign",
  "Blood Sacrifice",
  "Brawn",
  "Brittle Barrier",
  "Brutal Restraint",
  "Brute Force Solution",
  "Fortified Legion",
  "Calamitous Visions",
  "Careful Planning",
  "Cheap Construction",
  "Chill of Corruption",
  "Clear Mind",
  "Coated Shrapnel",
  "Cold Steel",
  "Collateral Damage",
  "Combat Focus",
  "Combat Focus",
  "Combat Focus",
  "Combustibles",
  "Conqueror's Efficiency",
  "Conqueror's Longevity",
  "Conqueror's Potency",
  "Corrupted Energy",
  "Dead Reckoning",
  "Divide and Conquer",
  "Efficient Training",
  "Eldritch Knowledge",
  "Elegant Hubris",
  "Emperor's Cunning",
  "Emperor's Mastery",
  "Emperor's Might",
  "Emperor's Wit",
  "Endless Misery",
  "Energised Armour",
  "Energy From Within",
  "Fertile Mind",
  "Fevered Mind",
  "Fight for Survival",
  "Fireborn",
  "First Snow",
  "Fluid Motion",
  "Fortress Covenant",
  "Fragile Bloom",
  "Fragility",
  "From Dust",
  "Frozen Trail",
  "Glorious Vanity",
  "Grand Spectrum",
  "Grand Spectrum",
  "Grand Spectrum",
  "Growing Agony",
  "Hair Trigger",
  "Hazardous Research",
  "Healthy Mind",
  "Hidden Potential",
  "Hotheaded",
  "Hungry Abyss",
  "Inertia",
  "Inevitability",
  "Inspired Learning",
  "Intuitive Leap",
  "Izaro's Turmoil",
  "Kitava's Teachings",
  "Lethal Pride",
  "Lioneye's Fall",
  "Lord of Steel",
  "Malicious Intent",
  "Mantra of Flames",
  "Martial Artistry",
  "Megalomaniac",
  "Might and Influence",
  "Might in All Forms",
  "Might of the Meek",
  "Militant Faith",
  "Mutated Growth",
  "Nadir Mode",
  "Natural Affinity",
  "Omen on the Winds",
  "One With Nothing",
  "Overwhelming Odds",
  "Pacifism",
  "Pitch Darkness",
  "Poacher's Aim",
  "Powerlessness",
  "Primordial Eminence",
  "Primordial Harmony",
  "Primordial Might",
  "Pugilist",
  "Pure Talent",
  "Quickening Covenant",
  "Rain of Splinters",
  "Rapid Expansion",
  "Reckless Defence",
  "Replica Blood Sacrifice",
  "Replica Cheap Construction",
  "Replica Conqueror's Efficiency",
  "Replica Fragile Bloom",
  "Replica Hotheaded",
  "Replica Primordial Might",
  "Replica Pure Talent",
  "Replica Reckless Defence",
  "Replica Unstable Payload",
  "Ring of Blades",
  "Rolling Flames",
  "Sacrificial Harvest",
  "Self-Flagellation",
  "Shattered Chains",
  "Soul's Wick",
  "Spire of Stone",
  "Spirited Response",
  "Spirit Guards",
  "Split Personality",
  "Spreading Rot",
  "Static Electricity",
  "Steel Spirit",
  "Sudden Ignition",
  "Survival Instincts",
  "Survival Secrets",
  "Survival Skills",
  "Tempered Flesh",
  "Tempered Mind",
  "Tempered Spirit",
  "The Anima Stone",
  "The Blue Dream",
  "The Blue Nightmare",
  "The Front Line",
  "The Golden Rule",
  "The Green Dream",
  "The Green Nightmare",
  "The Interrogation",
  "The Long Winter",
  "The Red Dream",
  "The Red Nightmare",
  "The Siege",
  "The Vigil",
  "Thread of Hope",
  "Transcendent Flesh",
  "Transcendent Mind",
  "Transcendent Spirit",
  "Unending Hunger",
  "Unnatural Instinct",
  "Unstable Payload",
  "Vaal Sentencing",
  "Violent Dead",
  "Voices",
  "Volley Fire",
  "Warlord's Reach",
  "Watcher's Eye",
  "Weight of Sin",
  "Weight of the Empire",
  "Wildfire",
  "Winter Burial",
  "Winter's Bounty",
]

export const prophecies = [
  "The Alchemist",
  "Anarchy's End I",
  "Anarchy's End II",
  "Anarchy's End III",
  "Anarchy's End IV",
  "Ancient Rivalries I",
  "Ancient Rivalries II",
  "Ancient Rivalries III",
  "Ancient Rivalries IV",
  "The Twins",
  "Possessed Foe",
  "The Invader",
  "Visions of the Drowned",
  "Monstrous Treasure",
  "Vaal Invasion",
  "The Hungering Swarm",
  "The Trembling Earth",
  "The Cursed Choir",
  "Soil, Worms and Blood",
  "The Jeweller's Touch",
  "The Forgotten Garrison",
  "Song of the Sekhema",
  "The Queen's Vaults",
  "The Queen's Sacrifice",
  "Beyond Sight I",
  "Beyond Sight II",
  "Beyond Sight III",
  "Beyond Sight IV",
  "Cold Blooded Fury",
  "Reforged Bonds",
  "Last of the Wildmen",
  "Cold Greed",
  "A Valuable Combination",
  "The Fortune Teller's Collection",
  "The Child of Lunaris",
  "Faith Exhumed",
  "Twice Enchanted",
  "Day of Sacrifice I",
  "Day of Sacrifice II",
  "Day of Sacrifice III",
  "Day of Sacrifice IV",
  "Deadly Rivalry I",
  "Deadly Rivalry II",
  "Deadly Rivalry III",
  "Deadly Rivalry IV",
  "Deadly Rivalry V",
  "The Malevolent Witch",
  "Burning Dread",
  "Agony at Dusk",
  "Blinding Light",
  "The Wealthy Exile",
  "The Scout",
  "Fallow At Last",
  "Trapped in the Tower",
  "Dark Instincts",
  "Plague of Frogs",
  "Black Devotion",
  "The Bishop's Legacy",
  "Pools of Wealth",
  "Crimson Hues",
  "A Vision of Ice and Fire",
  "The Blacksmith",
  "A Dishonourable Death",
  "End of the Light",
  "Nemesis of Greed",
  "Battle Hardened",
  "Trash to Treasure",
  "The Emperor's Trove",
  "Path of Betrayal",
  "From The Void",
  "The Misunderstood Queen",
  "Nature's Resilience",
  "The Snuffed Flame",
  "The King and the Brambles",
  "Mouth of Horrors",
  "The Servant's Heart",
  "The Karui Rebellion",
  "The Bloody Flowers Redux",
  "The Beginning and the End",
  "Heavy Blows",
  "Dying Cry",
  "Fire and Ice",
  "Severed Limbs",
  "Fire and Brimstone",
  "The Apex Predator",
  "The Silverwood",
  "The King's Path",
  "Hidden Reinforcements",
  "The Bowstring's Music",
  "Rebirth",
  "Power Magnified",
  "Gilded Within",
  "Ending the Torment",
  "Hunter's Lesson",
  "Pleasure and Pain",
  "The Flow of Energy",
  "Winter's Mournful Melodies",
  "A Forest of False Idols",
  "Erased from Memory",
  "Ancient Doom",
  "The Nightmare Awakens",
  "The Dreamer's Dream",
  "The Dream Trial",
  "Hidden Vaal Pathways",
  "Echoes of Lost Love",
  "Echoes of Witchcraft",
  "A Master Seeks Help",
  "A Master Seeks Help",
  "A Master Seeks Help",
  "A Master Seeks Help",
  "Bountiful Traps",
  "A Master Seeks Help",
  "The God of Misfortune",
  "Brothers in Arms",
  "Echoes of Mutation",
  "The Aesthete's Spirit",
  "The Undead Brutes",
  "The Four Feral Exiles",
  "Vaal Winds",
  "Fire from the Sky",
  "Ice from Above",
  "Lightning Falls",
  "Crushing Squall",
  "The Undead Storm",
  "Deadly Twins",
  "A Gracious Master",
  "The Mentor",
  "Overflowing Riches",
  "Mysterious Invaders",
  "Thaumaturgical History I",
  "Thaumaturgical History II",
  "Thaumaturgical History III",
  "Thaumaturgical History IV",
  "Forceful Exorcism",
  "The Fall of an Empire",
  "The Last Watch",
  "The Soulless Beast",
  "Custodians of Silence",
  "The Prison Guard",
  "The Prison Key",
  "The Ward's Ward",
  "The Lady in Black",
  "The Brutal Enforcer",
  "Flesh of the Beast",
  "Storm on the Horizon",
  "The Nest",
  "Abnormal Effulgence",
  "Fire, Wood and Stone",
  "Baptism by Death",
  "Fear's Wide Reach",
  "Against the Tide",
  "From Death Springs Life",
  "Weeping Death",
  "Storm on the Reef",
  "Strong as a Bull",
  "Graceful Flames",
  "A Whispered Prayer",
  "Wind and Thunder",
  "The Flayed Man",
  "Blood of the Betrayed",
  "Defiled in the Sceptre",
  "The Sword King's Passion",
  "Blood in the Eyes",
  "Risen Blood",
  "The Eagle's Cry",
  "Roth's Legacy",
  "The Petrified",
  "Notched Flesh",
  "The Walking Mountain",
  "A Firm Foothold",
  "The Sinner's Stone",
  "The Lost Undying",
  "A Prodigious Hand",
  "A Call into the Void",
  "The Hollow Pledge",
  "Lost in the Pages",
  "Cleanser of Sins",
  "Heart of the Fire",
  "The Vanguard",
  "The Watcher's Watcher",
  "Plague of Rats",
  "Lasting Impressions",
  "Kalandra's Craft",
  "The Dreaded Rhoa",
  "Fated Connections",
  "A Regal Death",
  "The Mysterious Gift",
  "Erasmus' Gift",
  "The Brothers of Necromancy",
  "An Unseen Peril",
  "Waiting in Ambush",
  "Sun's Punishment",
  "The Ambitious Bandit I",
  "The Ambitious Bandit II",
  "The Ambitious Bandit III",
  "Dance of Steel",
  "The Feral Lord I",
  "The Feral Lord II",
  "The Feral Lord III",
  "The Feral Lord IV",
  "The Feral Lord V",
  "Blind Faith",
  "The Great Mind of the North",
  "The Great Leader of the North",
  "The Plaguemaw I",
  "The Plaguemaw II",
  "The Plaguemaw III",
  "The Plaguemaw IV",
  "The Plaguemaw V",
  "The Stockkeeper",
  "The Storm Spire",
  "The Unbreathing Queen I",
  "The Unbreathing Queen II",
  "The Unbreathing Queen III",
  "The Unbreathing Queen IV",
  "The Unbreathing Queen V",
  "The Warmongers I",
  "The Warmongers II",
  "The Warmongers III",
  "The Warmongers IV",
  "The Lost Maps",
  "A Rift in Time",
  "The Singular Spirit",
  "Touched by the Wind",
  "Resistant to Change",
  "Smothering Tendrils",
  "Vital Transformation",
  "Golden Touch",
  "Holding the Bridge",
  "Unbearable Whispers I",
  "Unbearable Whispers II",
  "Unbearable Whispers III",
  "Unbearable Whispers IV",
  "Unbearable Whispers V",
  "Undead Uprising",
  "Living Fires",
  "Unnatural Energy",
  "In the Grasp of Corruption",
  "The Hardened Armour",
  "The Beautiful Guide",
  "The Sharpened Blade",
  "The Corrupt",
  "The Forgotten Soldiers",
  "Darktongue's Shriek",
  "Greed's Folly"
]
// add other key to object pattern, unique = true.
export const result = [
  {
    label: "Accessories",
    entries: removeDuplicates(accessories),
  },
  {
    label: "Armours",
    entries: removeDuplicates(armours),
  },
  {
    label: "Weapons",
    entries: removeDuplicates(weapons),
  },
  {
    label: "Currency",
    entries: removeDuplicates(currency),
  },
  {
    label: "Cards",
    entries: removeDuplicates(cards),
  },
  {
    label: "Flasks",
    entries: removeDuplicates(flasks)
  },
  {
    label: "Gems",
    entries: removeDuplicates(gems)
  },
  {
    label: "Jewels",
    entries: removeDuplicates(jewels)
  },
  {
    label: "Prophecies",
    entries: removeDuplicates(prophecies)
  }
];

function removeDuplicates(array) {
  return [...new Set(array)];
}

// LARGE STACK
export const stack = removeDuplicates(accessories.concat(armours));

/*
let result = items.map((item) => {
  return item["name"]
})
*/



