export const accessories = [
  "Meginord's Girdle",
  "Gloomfang",
  "Ungil's Harmony",
  "Doedre's Damning",
  "Marylene's Fallacy",
  "Malachai's Artifice",
  "Andvarius",
  "Blackheart",
  "Perandus Signet",
  "Bated Breath",
  "Lori's Lantern",
  "Daresso's Salute",
  "Immortal Flesh",
  "Rashkaldor's Patience",
  "Thief's Torment",
  "Essence Worm",
  "Heartbound Loop",
  "Headhunter",
  "Precursor's Emblem",
  "Sibyl's Lament",
  "Ming's Heart",
  "Maligaro's Cruelty",
  "Tavukai",
  "Shaper's Seed",
  "Le Heup of All",
  "Stormfire",
  "Araku Tiki",
  "Darkness Enthroned",
  "The Anvil",
  "The Halcyon",
  "The Taming",
  "Ventor's Gamble",
  "Circle of Guilt",
  "Voll's Devotion",
  "String of Servitude",
  "Perandus Blazon",
  "Karui Charge",
  "Sacrificial Heart",
  "Timeclasp",
  "Dream Fragments",
  "Warped Timepiece",
  "Profane Proxy",
  "The Pandemonius",
  "Siegebreaker",
  "Leash of Oblation",
  "Karui Ward",
  "The Nomad",
  "Yoke of Suffering",
  "Tear of Purity",
  "Faminebind",
  "Mark of the Shaper",
  "Atziri's Foible",
  "Ngamahu Tiki",
  "Doryani's Invitation",
  "The Retch",
  "The Aylardex",
  "The Ignomon",
  "Stone of Lazhwar",
  "Kikazaru",
  "Death Rush",
  "Bisco's Collar",
  "Bloodboil",
  "Prismweave",
  "Pyre",
  "Belt of the Deceiver",
  "Wurm's Molt",
  "Retaliation Charm",
  "Circle of Anguish",
  "Circle of Regret",
  "The Ascetic",
  "Rigwald's Curse",
  "Badge of the Brotherhood",
  "Ascent From Flesh",
  "Aul's Uprising",
  "Carnage Heart",
  "Victario's Acuity",
  "Circle of Fear",
  "The Pariah",
  "Xoph's Blood",
  "Romira's Banquet",
  "The Flow Untethered",
  "Berek's Pass",
  "Sidhebreath",
  "Berek's Grip",
  "Ryslatha's Coil",
  "Praxis",
  "The Jinxed Juju",
  "Vivinsect",
  "Snakepit",
  "The Hungry Loop",
  "Mokou's Embrace",
  "Sunblast",
  "Astramentis",
  "Eye of Chayula",
  "Fury Valve",
  "Kaom's Way",
  "Circle of Nostalgia",
  "Willowgift",
  "Hyrri's Truth",
  "Kaom's Sign",
  "Impresence",
  "Putembo's Valley",
  "Bisco's Leash",
  "Choir of the Storm",
  "Ahkeli's Valley",
  "Gluttony",
  "Coward's Legacy",
  "Perquil's Toe",
  "Voideye",
  "Bloodgrip",
  "Winterheart",
  "Voidheart",
  "Dyadian Dawn",
  "Mark of the Elder",
  "Soul Tether",
  "Cyclopean Coil",
  "Blood of Corruption",
  "Solstice Vigil",
  "The Warden's Brand",
  "Maligaro's Restraint",
  "Icefang Orbit",
  "The Magnate",
  "Timetwist",
  "Shavronne's Revelation",
  "Star of Wraeclast",
  "Presence of Chayula",
  "Call of the Brotherhood",
  "The Primordial Chain",
  "Coward's Chains",
  "Putembo's Meadow",
  "Gifts from Above",
  "The Torrent's Reclamation",
  "Storm Secret",
  "Night's Hold",
  "Umbilicus Immortalis",
  "Uzaza's Mountain",
  "Venopuncture",
  "Mutewind Seal",
  "Extractor Mentis",
  "Brinerot Mark",
  "The Effigon",
  "Soulthirst",
  "Ahkeli's Meadow",
  "Rigwald's Crest",
  "Perseverance",
  "Xoph's Heart",
  "Mark of Submission",
  "Berek's Respite",
  "Feastbind",
  "Emberwake",
  "Hinekora's Sight",
  "Ngamahu's Sign",
  "Astral Projector",
  "Mother's Embrace",
  "Tasalio's Sign",
  "Uzaza's Valley",
  "Eyes of the Greatwolf",
  "Demigod's Eye",
  "Voice of the Storm",
  "Valyrium",
  "Redblade Band",
  "Hyperboreus",
  "The Tactician",
  "Natural Hierarchy",
  "Uzaza's Meadow",
  "Putembo's Mountain",
  "Blightwell",
  "Ahkeli's Mountain",
  "Auxium",
  "Demigod's Bounty",
  "Valako's Sign",
  "Eye of Innocence",
  "Bear's Girdle",
  "The Felbog Fang",
  "Winterweave",
  "Warrior's Legacy",
  "Zerphi's Heart",
  "Pyroshock Clasp",
  "The Ephemeral Bond",
  "The Highwayman",
  "The Druggery",
  "Replica Hyrri's Truth",
  "Replica Soul Tether",
  "Replica Prismweave",
  "Replica Karui Ward",
  "Replica Headhunter",
];

export const armours = [
  "Wreath of Phrecia",
  "Rainbowstride",
  "The Peregrine",
  "Emperor's Vigilance",
  "The Fracturing Spinner",
  "Darkray Vectors",
  "The Vertex",
  "Fractal Thoughts",
  "Ezomyte Peak",
  "Abyssus",
  "Great Old One's Tentacles",
  "Crown of the Inward Eye",
  "Wraithlord",
  "Mark of the Red Covenant",
  "Snakebite",
  "Asphyxia's Wrath",
  "Tabula Rasa",
  "Veruso's Battering Rams",
  "Rat's Nest",
  "The Formless Flame",
  "Steppan Eard",
  "Lochtonial Caress",
  "Alpha's Howl",
  "The Baron",
  "Demon Stitcher",
  "Esh's Visage",
  "Shadows and Dust",
  "Atziri's Acuity",
  "Shavronne's Wrappings",
  "Farrul's Fur",
  "Frostferno",
  "Queen of the Forest",
  "Gorgon's Gaze",
  "Vix Lunaris",
  "Surgebinders",
  "Bronn's Lithe",
  "Kaom's Heart",
  "Tombfist",
  "Soul Strike",
  "Wildwrap",
  "Facebreaker",
  "The Surrender",
  "Geofri's Sanctuary",
  "Command of the Pit",
  "Incandescent Heart",
  "Cospri's Will",
  "Carcass Jack",
  "Bubonic Trail",
  "Farrul's Fur",
  "Starkonja's Head",
  "Skin of the Lords",
  "Matua Tupuna",
  "Great Old One's Ward",
  "Asenath's Mark",
  "Hrimnor's Resolve",
  "The Eternal Apple",
  "Scold's Bridle",
  "The Embalmer",
  "Inpulsa's Broken Heart",
  "Shaper's Touch",
  "Painseeker",
  "Sadima's Touch",
  "Kalisa's Grace",
  "Abberath's Hooves",
  "Offering to the Serpent",
  "Kongming's Stratagem",
  "Wyrmsign",
  "Skirmish",
  "Ambu's Charge",
  "Geofri's Crest",
  "Soul Mantle",
  "Kingsguard",
  "Cherrubim's Maleficence",
  "Brinerot Whalers",
  "Wanderlust",
  "The Eternity Shroud",
  "Windshriek",
  "Thundersight",
  "The Covenant",
  "Lightpoacher",
  "Volkuur's Guidance",
  "Eber's Unification",
  "Sunspite",
  "Crystal Vault",
  "Memory Vault",
  "Gang's Momentum",
  "Stormcharger",
  "Ralakesh's Impatience",
  "Atziri's Splendour",
  "Loreweave",
  "Soul Mantle",
  "The Unshattered Will",
  "Honourhome",
  "Giantsbane",
  "Wondertrap",
  "Daresso's Defiance",
  "The Three Dragons",
  "Deerstalker",
  "Rime Gaze",
  "Kingsguard",
  "Three-step Assault",
  "Lioneye's Paws",
  "Beacon of Madness",
  "Saqawal's Talons",
  "Fenumus' Spinnerets",
  "Nomic's Storm",
  "Alberon's Warpath",
  "The Blood Dance",
  "Craiceann's Tracks",
  "Dance of the Offered",
  "Greedtrap",
  "Victario's Flight",
  "Atziri's Step",
  "Redblade Tramplers",
  "The Infinite Pursuit",
  "Shavronne's Gambit",
  "Kaom's Roots",
  "Goldwyrm",
  "The Stampede",
  "Sin Trek",
  "Voidwalker",
  "Duskblight",
  "Torchoak Step",
  "Mutewind Whispersteps",
  "Bones of Ullr",
  "Yriel's Fostering",
  "Devoto's Devotion",
  "Mask of the Tribunal",
  "Craiceann's Pincers",
  "Flesh and Spirit",
  "Hrimsorrow",
  "The Gull",
  "Southbound",
  "Saqawal's Winds",
  "Shackles of the Wretched",
  "Storm's Gift",
  "Drillneck",
  "Maloney's Nightfall",
  "Aurseize",
  "Doedre's Tenure",
  "Infernal Mantle",
  "Haemophilia",
  "Victario's Influence",
  "Blasphemer's Grasp",
  "Carcass Jack",
  "Skyforth",
  "Tinkerskin",
  "Tinkerskin",
  "Curtain Call",
  "The Devouring Diadem",
  "Hands of the High Templar",
  "Voidfletcher",
  "Sundance",
  "Slitherpinch",
  "Dendrobate",
  "Skullhead",
  "Thousand Teeth Temu",
  "Lioneye's Vision",
  "Saffell's Frame",
  "Hale Negator",
  "Shroud of the Lightless",
  "The Deep One's Hide",
  "Bronn's Lithe",
  "Vis Mortis",
  "Daresso's Defiance",
  "The Covenant",
  "The Coming Calamity",
  "Hyrri's Ire",
  "Soul Mantle",
  "Fleshcrafter",
  "Gruthkul's Pelt",
  "Atziri's Splendour",
  "Dendrobate",
  "Belly of the Beast",
  "The Beast Fur Shawl",
  "Victario's Influence",
  "The Brass Dome",
  "Lioneye's Vision",
  "Cherrubim's Maleficence",
  "The Ivory Tower",
  "Sporeguard",
  "Cloak of Defiance",
  "Craiceann's Carapace",
  "Maloney's Mechanism",
  "The Tempest's Binding",
  "Assailum",
  "Whakatutuki o Matua",
  "Triad Grip",
  "Iron Heart",
  "Oskarm",
  "Sentari's Answer",
  "Jaws of Agony",
  "Blackgleam",
  "The Anticipation",
  "Saqawal's Flock",
  "Bitterbind Point",
  "Death's Oath",
  "Worldcarver",
  "Light of Lunaris",
  "Vixen's Entrapment",
  "Seven-League Step",
  "Malachai's Simula",
  "Atziri's Mirror",
  "Crown of Thorns",
  "Hyrri's Bite",
  "Malachai's Loop",
  "Shavronne's Pace",
  "Veil of the Night",
  "The Restless Ward",
  "Thunderfist",
  "Maligaro's Lens",
  "Doedre's Scorn",
  "Lightning Coil",
  "Crown of Eyes",
  "Doedre's Skin",
  "Lightbane Raiment",
  "Chernobog's Pillar",
  "Loreweave",
  "Prism Guardian",
  "Heretic's Veil",
  "Maligaro's Virtuosity",
  "Empire's Grasp",
  "Black Sun Crest",
  "Voidbringer",
  "The Brine Crown",
  "The Ivory Tower",
  "The Queen's Hunger",
  "The Broken Crown",
  "Yriel's Fostering",
  "Thousand Ribbons",
  "Victario's Charity",
  "Heatshiver",
  "Ondar's Clasp",
  "Perepiteia",
  "Craiceann's Chitin",
  "Perfidy",
  "Manastorm",
  "Aegis Aurora",
  "Invictus Solaris",
  "Dialla's Malefaction",
  "Icetomb",
  "Vaal Caress",
  "Loreweave",
  "March of the Legion",
  "Maw of Conquest",
  "Solaris Lorica",
  "Windscream",
  "Magna Eclipsis",
  "Rise of the Phoenix",
  "Esh's Mirror",
  "Fox's Fortune",
  "Kaltensoul",
  "Geofri's Legacy",
  "Craghead",
  "Thirst for Horrors",
  "Deidbellow",
  "Hyrri's Demise",
  "Cragfall",
  "Lioneye's Remorse",
  "Doedre's Malevolence",
  "Malachai's Mark",
  "Asenath's Gentle Touch",
  "The Bringer of Rain",
  "Eye of Malice",
  "The Red Trail",
  "Chains of Command",
  "Yriel's Fostering",
  "Foxshade",
  "Mask of the Spirit Drinker",
  "The Brass Dome",
  "Farrul's Chase",
  "Belly of the Beast",
  "Doryani's Delusion",
  "Null and Void",
  "Ahn's Heritage",
  "Fenumus' Toxins",
  "Fenumus' Shroud",
  "Allelopathy",
  "Meginord's Vise",
  "Wheel of the Stormsail",
  "Grip of the Council",
  "Saqawal's Nest",
  "Zahndethus' Cassock",
  "Cowl of the Thermophile",
  "Cowl of the Ceraunophile",
  "Unyielding Flame",
  "Vis Mortis",
  "Scorpion's Call",
  "Wake of Destruction",
  "Redblade Banner",
  "Deidbell",
  "Breathstealer",
  "Lycosidae",
  "Wall of Brambles",
  "Leper's Alms",
  "Martyr's Crown",
  "Rathpith Globe",
  "Goldrim",
  "The Formless Inferno",
  "Dendrobate",
  "Icetomb",
  "Rigwald's Quills",
  "Rotting Legion",
  "Voll's Protector",
  "The Shattered Divinity",
  "The Tempest's Liberation",
  "Obscurantis",
  "Cloak of Flame",
  "The Rat Cage",
  "The Restless Ward",
  "Doryani's Fist",
  "Winds of Change",
  "Voll's Vision",
  "Brinerot Flag",
  "Trolltimber Spire",
  "Icetomb",
  "The Snowblind Grace",
  "Indigon",
  "Chalice of Horrors",
  "Flamesight",
  "Saemus' Gift",
  "Fairgraves' Tricorne",
  "Leer Cast",
  "Galesight",
  "Kaltenhalt",
  "Ashrend",
  "Tukohama's Fortress",
  "Skin of the Loyal",
  "Inya's Epiphany",
  "The Queen's Hunger",
  "Bloodbond",
  "Dusktoe",
  "Geofri's Sanctuary",
  "Zeel's Amplifier",
  "Cloak of Defiance",
  "Perfidy",
  "Briskwrap",
  "Algor Mortis",
  "Solaris Lorica",
  "The Iron Fortress",
  "Bronn's Lithe",
  "Lightning Coil",
  "Infernal Mantle",
  "The Restless Ward",
  "Mistwall",
  "Atziri's Reflection",
  "Infernal Mantle",
  "Speaker's Wreath",
  "Kintsugi",
  "Doedre's Skin",
  "Shavronne's Wrappings",
  "Bloodbond",
  "Cloak of Tawm'r Isley",
  "The Signal Fire",
  "Repentance",
  "Zahndethus' Cassock",
  "Chains of Command",
  "Incandescent Heart",
  "Chains of Command",
  "Doedre's Skin",
  "Cherrubim's Maleficence",
  "Kingsguard",
  "The Covenant",
  "Bloodbond",
  "Fenumus' Shroud",
  "Fenumus' Weave",
  "Daresso's Courage",
  "Ashrend",
  "Queen of the Forest",
  "The Coming Calamity",
  "Mind of the Council",
  "Apep's Supremacy",
  "Springleaf",
  "Mindspiral",
  "Broken Faith",
  "Mutewind Pennant",
  "Bramblejack",
  "Inpulsa's Broken Heart",
  "The Perfect Form",
  "Greed's Embrace",
  "Omeyocan",
  "Greed's Embrace",
  "Aukuna's Will",
  "Farrul's Fur",
  "Asenath's Chant",
  "Cospri's Will",
  "Doryani's Prototype",
  "Demigod's Beacon",
  "Demigod's Dominance",
  "Crest of Perandus",
  "Garb of the Ephemeral",
  "Dialla's Malefaction",
  "Fleshcrafter",
  "Glitterdisc",
  "Ambu's Charge",
  "Farrul's Pounce",
  "Cowl of the Cryophile",
  "Crown of the Tyrant",
  "Titucius' Span",
  "Crown of the Pale King",
  "Farrul's Bite",
  "The Queen's Hunger",
  "Saqawal's Nest",
  "Shadowstitch",
  "The Rat Cage",
  "Garb of the Ephemeral",
  "Mask of the Stitched Demon",
  "Malachai's Vision",
  "Dialla's Malefaction",
  "Cloak of Flame",
  "Ahn's Contempt",
  "Apep's Slumber",
  "Fox's Fortune",
  "Wall of Brambles",
  "Atziri's Splendour",
  "Chitus' Apex",
  "Hrimburn",
  "Death's Oath",
  "The Perfect Form",
  "Greed's Embrace",
  "Thousand Ribbons",
  "Victario's Influence",
  "Kitava's Thirst",
  "Foxshade",
  "Lightning Coil",
  "The Beast Fur Shawl",
  "Malachai's Awakening",
  "Foxshade",
  "Ambu's Charge",
  "Craiceann's Carapace",
  "Briskwrap",
  "Daresso's Defiance",
  "Death's Door",
  "Demigod's Triumph",
  "Rearguard",
  "Architect's Hand",
  "Garukhan's Flight",
  "Fox's Fortune",
  "The Perfect Form",
  "Ezomyte Hold",
  "Machina Mitts",
  "Rotting Legion",
  "Death's Oath",
  "Kintsugi",
  "Rotting Legion",
  "Ylfeban's Trickery",
  "Bramblejack",
  "Perfidy",
  "The Iron Fortress",
  "Wildwrap",
  "Deshret's Vise",
  "Wall of Brambles",
  "Crystal Vault",
  "The Oak",
  "Voll's Protector",
  "Iron Heart",
  "The Eternity Shroud",
  "Plume of Pursuit",
  "Viper's Scales",
  "Slavedriver's Hand",
  "Solaris Lorica",
  "Broadstroke",
  "The Iron Fortress",
  "Lightbane Raiment",
  "Ashrend",
  "Iron Heart",
  "Gruthkul's Pelt",
  "Garb of the Ephemeral",
  "Doryani's Prototype",
  "Briskwrap",
  "Forbidden Shako",
  "Abhorrent Interrogation",
  "The Immortal Will",
  "Willclash",
  "The Ghastly Theatre",
  "Mercenary's Lot",
  "Crest of Desire",
  "Blunderbore",
  "Expedition's End",
  "Replica Grip of the Council",
  "Replica Perfect Form",
  "Replica Alberon's Warpath",
  "Replica Inya's Epiphany",
  "Replica Eternity Shroud",
  "Replica Atziri's Acuity",
  "Replica Red Trail",
  "Replica Maloney's Mechanism",
  "Replica Ambu's Charge",
  "Replica Voidwalker",
  "Replica Kaom's Heart",
  "Replica Mistwall",
  "Replica Bones of Ullr",
  "Replica Farrul's Fur",
  "Replica Shroud of the Lightless",
  "Maw of Mischief",
  "The Fledgling",
  "Corpsewalker",
];

/* 

Go through each object and iterate the object on chrome console to grab all array entries

*/

export const currency = [
  "Orb of Alteration",
  "Orb of Fusing",
  "Orb of Alchemy",
  "Chaos Orb",
  "Gemcutter's Prism",
  "Exalted Orb",
  "Chromatic Orb",
  "Jeweller's Orb",
  "Engineer's Orb",
  "Infused Engineer's Orb",
  "Orb of Chance",
  "Cartographer's Chisel",
  "Orb of Scouring",
  "Blessed Orb",
  "Orb of Regret",
  "Regal Orb",
  "Divine Orb",
  "Vaal Orb",
  "Orb of Annulment",
  "Orb of Binding",
  "Ancient Orb",
  "Orb of Horizons",
  "Harbinger's Orb",
  "Scroll of Wisdom",
  "Portal Scroll",
  "Armourer's Scrap",
  "Blacksmith's Whetstone",
  "Glassblower's Bauble",
  "Orb of Transmutation",
  "Orb of Augmentation",
  "Mirror of Kalandra",
  "Eternal Orb",
  "Perandus Coin",
  "Silver Coin",
  "Crusader's Exalted Orb",
  "Redeemer's Exalted Orb",
  "Hunter's Exalted Orb",
  "Warlord's Exalted Orb",
  "Awakener's Orb",
  "Facetor's Lens",
  "Rogue's Marker",
  "Prime Regrading Lens",
  "Secondary Regrading Lens",
  "Tempering Orb",
  "Tailoring Orb",
  "Annulment Shard",
  "Mirror Shard",
  "Exalted Shard",
  "Binding Shard",
  "Horizon Shard",
  "Harbinger's Shard",
  "Engineer's Shard",
  "Ancient Shard",
  "Chaos Shard",
  "Regal Shard",
  "Simple Sextant",
  "Prime Sextant",
  "Awakened Sextant",
  "Blessing of Xoph",
  "Blessing of Tul",
  "Blessing of Esh",
  "Blessing of Uul-Netol",
  "Blessing of Chayula",
  "Splinter of Xoph",
  "Splinter of Tul",
  "Splinter of Esh",
  "Splinter of Uul-Netol",
  "Splinter of Chayula",
  "Timeless Karui Splinter",
  "Timeless Maraketh Splinter",
  "Timeless Eternal Empire Splinter",
  "Timeless Templar Splinter",
  "Timeless Vaal Splinter",
  "Simulacrum Splinter",
  "Stacked Deck",
];

export const cards = [
  "A Dab of Ink",
  "A Familiar Call",
  "A Mother's Parting Gift",
  "A Note in the Wind",
  "Abandoned Wealth",
  "Akil's Prophecy",
  "Alluring Bounty",
  "Alone in the Darkness",
  "Anarchy's Price",
  "Arrogance of the Vaal",
  "Assassin's Favour",
  "Atziri's Arsenal",
  "Audacity",
  "Azyran's Reward",
  "Baited Expectations",
  "Beauty Through Death",
  "Birth of the Three",
  "Blessing of God",
  "Blind Venture",
  "Boon of Justice",
  "Boon of the First Ones",
  "Boundless Realms",
  "Bowyer's Dream",
  "Brother's Stash",
  "Buried Treasure",
  "Burning Blood",
  "Call to the First Ones",
  "Cameria's Cut",
  "Cartographer's Delight",
  "Chaotic Disposition",
  "Council of Cats",
  "Coveted Possession",
  "Cursed Words",
  "Dark Dreams",
  "Dark Temptation",
  "Death",
  "Deathly Designs",
  "Demigod's Wager",
  "Desecrated Virtue",
  "Destined to Crumble",
  "Dialla's Subjugation",
  "Divine Justice",
  "Doedre's Madness",
  "Dying Anguish",
  "Earth Drinker",
  "Echoes of Love",
  "Emperor of Purity",
  "Emperor's Luck",
  "Etched in Blood",
  "Forbidden Power",
  "Friendship",
  "Gemcutter's Promise",
  "Gift of Asenath",
  "Gift of the Gemling Queen",
  "Glimmer of Hope",
  "Grave Knowledge",
  "Harmony of Souls",
  "Her Mask",
  "Heterochromia",
  "Hope",
  "House of Mirrors",
  "Hubris",
  "Humility",
  "Hunter's Resolve",
  "Hunter's Reward",
  "Immortal Resolve",
  "Imperial Legacy",
  "Jack in the Box",
  "Lantador's Lost Love",
  "Last Hope",
  "Left to Fate",
  "Light and Truth",
  "Lingering Remnants",
  "Lost Worlds",
  "Loyalty",
  "Luck of the Vaal",
  "Lucky Connections",
  "Lucky Deck",
  "Lysah's Respite",
  "Mawr Blaidd",
  "Merciless Armament",
  "Might is Right",
  "Mitts",
  "Monochrome",
  "More is Never Enough",
  "No Traces",
  "Nook's Crown",
  "Peaceful Moments",
  "Perfection",
  "Pride Before the Fall",
  "Pride of the First Ones",
  "Prometheus' Armoury",
  "Prosperity",
  "Rain of Chaos",
  "Rain Tempter",
  "Rats",
  "Rebirth",
  "Remembrance",
  "Sambodhi's Vow",
  "Scholar of the Seas",
  "Seven Years Bad Luck",
  "Shard of Fate",
  "Squandered Prosperity",
  "Struck by Lightning",
  "Succor of the Sinless",
  "The Academic",
  "The Admirer",
  "The Aesthete",
  "The Archmage's Right Hand",
  "The Arena Champion",
  "The Army of Blood",
  "The Artist",
  "The Avenger",
  "The Awakened",
  "The Bargain",
  "The Battle Born",
  "The Beast",
  "The Betrayal",
  "The Bitter Blossom",
  "The Blazing Fire",
  "The Body",
  "The Bones",
  "The Breach",
  "The Brittle Emperor",
  "The Cache",
  "The Cacophony",
  "The Calling",
  "The Carrion Crow",
  "The Cartographer",
  "The Cataclysm",
  "The Catalyst",
  "The Celestial Justicar",
  "The Celestial Stone",
  "The Chains that Bind",
  "The Cheater",
  "The Chosen",
  "The Coming Storm",
  "The Conduit",
  "The Craving",
  "The Cursed King",
  "The Damned",
  "The Dapper Prodigy",
  "The Dark Mage",
  "The Darkest Dream",
  "The Deal",
  "The Deceiver",
  "The Deep Ones",
  "The Demon",
  "The Demoness",
  "The Devastator",
  "The Doctor",
  "The Doppelganger",
  "The Dragon",
  "The Dragon's Heart",
  "The Dreamer",
  "The Dreamland",
  "The Drunken Aristocrat",
  "The Easy Stroll",
  "The Eldritch Decay",
  "The Encroaching Darkness",
  "The Endless Darkness",
  "The Endurance",
  "The Enlightened",
  "The Escape",
  "The Ethereal",
  "The Explorer",
  "The Eye of Terror",
  "The Eye of the Dragon",
  "The Fathomless Depths",
  "The Feast",
  "The Fiend",
  "The Fishmonger",
  "The Fletcher",
  "The Flora's Gift",
  "The Fool",
  "The Formless Sea",
  "The Forsaken",
  "The Fox",
  "The Gambler",
  "The Garish Power",
  "The Gemcutter",
  "The Gentleman",
  "The Gladiator",
  "The Golden Era",
  "The Greatest Intentions",
  "The Gulf",
  "The Hale Heart",
  "The Harvester",
  "The Hermit",
  "The Heroic Shot",
  "The Hive of Knowledge",
  "The Hoarder",
  "The Hunger",
  "The Immortal",
  "The Incantation",
  "The Innocent",
  "The Inoculated",
  "The Insatiable",
  "The Inventor",
  "The Iron Bard",
  "The Jester",
  "The Jeweller's Boon",
  "The Journalist",
  "The Journey",
  "The King's Blade",
  "The King's Heart",
  "The Landing",
  "The Last One Standing",
  "The Lich",
  "The Life Thief",
  "The Lion",
  "The Long Con",
  "The Lord in Black",
  "The Lord of Celebration",
  "The Lover",
  "The Lunaris Priestess",
  "The Mad King",
  "The Master",
  "The Master Artisan",
  "The Mayor",
  "The Mercenary",
  "The Messenger",
  "The Metalsmith's Gift",
  "The Mountain",
  "The Nurse",
  "The Oath",
  "The Obscured",
  "The Offering",
  "The Old Man",
  "The One With All",
  "The Opulent",
  "The Pack Leader",
  "The Pact",
  "The Penitent",
  "The Poet",
  "The Polymath",
  "The Porcupine",
  "The Price of Loyalty",
  "The Price of Protection",
  "The Primordial",
  "The Professor",
  "The Progeny of Lunaris",
  "The Puzzle",
  "The Queen",
  "The Rabid Rhoa",
  "The Realm",
  "The Risk",
  "The Rite of Elements",
  "The Road to Power",
  "The Ruthless Ceinture",
  "The Sacrifice",
  "The Saint's Treasure",
  "The Samurai's Eye",
  "The Scarred Meadow",
  "The Scavenger",
  "The Scholar",
  "The Seeker",
  "The Sephirot",
  "The Side Quest",
  "The Sigil",
  "The Siren",
  "The Skeleton",
  "The Soul",
  "The Spark and the Flame",
  "The Spoiled Prince",
  "The Standoff",
  "The Stormcaller",
  "The Strategist",
  "The Summoner",
  "The Sun",
  "The Surgeon",
  "The Surveyor",
  "The Survivalist",
  "The Sustenance",
  "The Sword King's Salute",
  "The Thaumaturgist",
  "The Throne",
  "The Tinkerer's Table",
  "The Tower",
  "The Traitor",
  "The Trial",
  "The Tumbleweed",
  "The Twilight Moon",
  "The Twins",
  "The Tyrant",
  "The Undaunted",
  "The Undisputed",
  "The Unexpected Prize",
  "The Union",
  "The Valkyrie",
  "The Valley of Steel Boxes",
  "The Vast",
  "The Visionary",
  "The Void",
  "The Warden",
  "The Warlord",
  "The Watcher",
  "The Web",
  "The White Knight",
  "The Wilted Rose",
  "The Wind",
  "The Witch",
  "The Wolf",
  "The Wolf's Legacy",
  "The Wolf's Shadow",
  "The Wolven King's Bite",
  "The Wolverine",
  "The World Eater",
  "The Wrath",
  "The Wretched",
  "Thirst for Knowledge",
  "Three Faces in the Dark",
  "Three Voices",
  "Thunderous Skies",
  "Time-Lost Relic",
  "Tranquillity",
  "Treasure Hunter",
  "Triskaidekaphobia",
  "Turn the Other Cheek",
  "Unchained",
  "Underground Forest",
  "Unrequited Love",
  "Vanity",
  "Vile Power",
  "Vinia's Token",
  "Void of the Elements",
  "Volatile Power",
  "Wealth and Power",
];

// add other key to object pattern, unique = true.
export const result = [
  {
    label: "Accessories",
    entries: removeDuplicates(accessories),
  },
  {
    label: "Armours",
    entries: removeDuplicates(armours),
  },
  {
    label: "Currency",
    entries: removeDuplicates(currency),
  },
  {
    label: "Cards",
    entries: removeDuplicates(cards),
  },
];

function removeDuplicates(array) {
  return [...new Set(array)];
}

// LARGE STACK
export const stack = removeDuplicates(accessories.concat(armours));

/*
let result = cards.map((card) => {
  return card["text"]
})
*/
