export const accessories = [
  "Meginord's Girdle",
  "Gloomfang",
  "Ungil's Harmony",
  "Doedre's Damning",
  "Marylene's Fallacy",
  "Malachai's Artifice",
  "Andvarius",
  "Blackheart",
  "Perandus Signet",
  "Bated Breath",
  "Lori's Lantern",
  "Daresso's Salute",
  "Immortal Flesh",
  "Rashkaldor's Patience",
  "Thief's Torment",
  "Essence Worm",
  "Heartbound Loop",
  "Headhunter",
  "Precursor's Emblem",
  "Sibyl's Lament",
  "Ming's Heart",
  "Maligaro's Cruelty",
  "Tavukai",
  "Shaper's Seed",
  "Le Heup of All",
  "Stormfire",
  "Araku Tiki",
  "Darkness Enthroned",
  "The Anvil",
  "The Halcyon",
  "The Taming",
  "Ventor's Gamble",
  "Circle of Guilt",
  "Voll's Devotion",
  "String of Servitude",
  "Perandus Blazon",
  "Karui Charge",
  "Sacrificial Heart",
  "Timeclasp",
  "Dream Fragments",
  "Warped Timepiece",
  "Profane Proxy",
  "The Pandemonius",
  "Siegebreaker",
  "Leash of Oblation",
  "Karui Ward",
  "The Nomad",
  "Yoke of Suffering",
  "Tear of Purity",
  "Faminebind",
  "Mark of the Shaper",
  "Atziri's Foible",
  "Ngamahu Tiki",
  "Doryani's Invitation",
  "The Retch",
  "The Aylardex",
  "The Ignomon",
  "Stone of Lazhwar",
  "Kikazaru",
  "Death Rush",
  "Bisco's Collar",
  "Bloodboil",
  "Prismweave",
  "Pyre",
  "Belt of the Deceiver",
  "Wurm's Molt",
  "Retaliation Charm",
  "Circle of Anguish",
  "Circle of Regret",
  "The Ascetic",
  "Rigwald's Curse",
  "Badge of the Brotherhood",
  "Ascent From Flesh",
  "Aul's Uprising",
  "Carnage Heart",
  "Victario's Acuity",
  "Circle of Fear",
  "The Pariah",
  "Xoph's Blood",
  "Romira's Banquet",
  "The Flow Untethered",
  "Berek's Pass",
  "Sidhebreath",
  "Berek's Grip",
  "Ryslatha's Coil",
  "Praxis",
  "The Jinxed Juju",
  "Vivinsect",
  "Snakepit",
  "The Hungry Loop",
  "Mokou's Embrace",
  "Sunblast",
  "Astramentis",
  "Eye of Chayula",
  "Fury Valve",
  "Kaom's Way",
  "Circle of Nostalgia",
  "Willowgift",
  "Hyrri's Truth",
  "Kaom's Sign",
  "Impresence",
  "Putembo's Valley",
  "Bisco's Leash",
  "Choir of the Storm",
  "Ahkeli's Valley",
  "Gluttony",
  "Coward's Legacy",
  "Perquil's Toe",
  "Voideye",
  "Bloodgrip",
  "Winterheart",
  "Voidheart",
  "Dyadian Dawn",
  "Mark of the Elder",
  "Soul Tether",
  "Cyclopean Coil",
  "Blood of Corruption",
  "Solstice Vigil",
  "The Warden's Brand",
  "Maligaro's Restraint",
  "Icefang Orbit",
  "The Magnate",
  "Timetwist",
  "Shavronne's Revelation",
  "Star of Wraeclast",
  "Presence of Chayula",
  "Call of the Brotherhood",
  "The Primordial Chain",
  "Coward's Chains",
  "Putembo's Meadow",
  "Gifts from Above",
  "The Torrent's Reclamation",
  "Storm Secret",
  "Night's Hold",
  "Umbilicus Immortalis",
  "Uzaza's Mountain",
  "Venopuncture",
  "Mutewind Seal",
  "Extractor Mentis",
  "Brinerot Mark",
  "The Effigon",
  "Soulthirst",
  "Ahkeli's Meadow",
  "Rigwald's Crest",
  "Perseverance",
  "Xoph's Heart",
  "Mark of Submission",
  "Berek's Respite",
  "Feastbind",
  "Emberwake",
  "Hinekora's Sight",
  "Ngamahu's Sign",
  "Astral Projector",
  "Mother's Embrace",
  "Tasalio's Sign",
  "Uzaza's Valley",
  "Eyes of the Greatwolf",
  "Demigod's Eye",
  "Voice of the Storm",
  "Valyrium",
  "Redblade Band",
  "Hyperboreus",
  "The Tactician",
  "Natural Hierarchy",
  "Uzaza's Meadow",
  "Putembo's Mountain",
  "Blightwell",
  "Ahkeli's Mountain",
  "Auxium",
  "Demigod's Bounty",
  "Valako's Sign",
  "Eye of Innocence",
  "Bear's Girdle",
  "The Felbog Fang",
  "Winterweave",
  "Warrior's Legacy",
  "Zerphi's Heart",
  "Pyroshock Clasp",
  "The Ephemeral Bond",
  "The Highwayman",
  "The Druggery",
  "Replica Hyrri's Truth",
  "Replica Soul Tether",
  "Replica Prismweave",
  "Replica Karui Ward",
  "Replica Headhunter",
];

export const armours = [
  "Wreath of Phrecia",
  "Rainbowstride",
  "The Peregrine",
  "Emperor's Vigilance",
  "The Fracturing Spinner",
  "Darkray Vectors",
  "The Vertex",
  "Fractal Thoughts",
  "Ezomyte Peak",
  "Abyssus",
  "Great Old One's Tentacles",
  "Crown of the Inward Eye",
  "Wraithlord",
  "Mark of the Red Covenant",
  "Snakebite",
  "Asphyxia's Wrath",
  "Tabula Rasa",
  "Veruso's Battering Rams",
  "Rat's Nest",
  "The Formless Flame",
  "Steppan Eard",
  "Lochtonial Caress",
  "Alpha's Howl",
  "The Baron",
  "Demon Stitcher",
  "Esh's Visage",
  "Shadows and Dust",
  "Atziri's Acuity",
  "Shavronne's Wrappings",
  "Farrul's Fur",
  "Frostferno",
  "Queen of the Forest",
  "Gorgon's Gaze",
  "Vix Lunaris",
  "Surgebinders",
  "Bronn's Lithe",
  "Kaom's Heart",
  "Tombfist",
  "Soul Strike",
  "Wildwrap",
  "Facebreaker",
  "The Surrender",
  "Geofri's Sanctuary",
  "Command of the Pit",
  "Incandescent Heart",
  "Cospri's Will",
  "Carcass Jack",
  "Bubonic Trail",
  "Farrul's Fur",
  "Starkonja's Head",
  "Skin of the Lords",
  "Matua Tupuna",
  "Great Old One's Ward",
  "Asenath's Mark",
  "Hrimnor's Resolve",
  "The Eternal Apple",
  "Scold's Bridle",
  "The Embalmer",
  "Inpulsa's Broken Heart",
  "Shaper's Touch",
  "Painseeker",
  "Sadima's Touch",
  "Kalisa's Grace",
  "Abberath's Hooves",
  "Offering to the Serpent",
  "Kongming's Stratagem",
  "Wyrmsign",
  "Skirmish",
  "Ambu's Charge",
  "Geofri's Crest",
  "Soul Mantle",
  "Kingsguard",
  "Cherrubim's Maleficence",
  "Brinerot Whalers",
  "Wanderlust",
  "The Eternity Shroud",
  "Windshriek",
  "Thundersight",
  "The Covenant",
  "Lightpoacher",
  "Volkuur's Guidance",
  "Eber's Unification",
  "Sunspite",
  "Crystal Vault",
  "Memory Vault",
  "Gang's Momentum",
  "Stormcharger",
  "Ralakesh's Impatience",
  "Atziri's Splendour",
  "Loreweave",
  "Soul Mantle",
  "The Unshattered Will",
  "Honourhome",
  "Giantsbane",
  "Wondertrap",
  "Daresso's Defiance",
  "The Three Dragons",
  "Deerstalker",
  "Rime Gaze",
  "Kingsguard",
  "Three-step Assault",
  "Lioneye's Paws",
  "Beacon of Madness",
  "Saqawal's Talons",
  "Fenumus' Spinnerets",
  "Nomic's Storm",
  "Alberon's Warpath",
  "The Blood Dance",
  "Craiceann's Tracks",
  "Dance of the Offered",
  "Greedtrap",
  "Victario's Flight",
  "Atziri's Step",
  "Redblade Tramplers",
  "The Infinite Pursuit",
  "Shavronne's Gambit",
  "Kaom's Roots",
  "Goldwyrm",
  "The Stampede",
  "Sin Trek",
  "Voidwalker",
  "Duskblight",
  "Torchoak Step",
  "Mutewind Whispersteps",
  "Bones of Ullr",
  "Yriel's Fostering",
  "Devoto's Devotion",
  "Mask of the Tribunal",
  "Craiceann's Pincers",
  "Flesh and Spirit",
  "Hrimsorrow",
  "The Gull",
  "Southbound",
  "Saqawal's Winds",
  "Shackles of the Wretched",
  "Storm's Gift",
  "Drillneck",
  "Maloney's Nightfall",
  "Aurseize",
  "Doedre's Tenure",
  "Infernal Mantle",
  "Haemophilia",
  "Victario's Influence",
  "Blasphemer's Grasp",
  "Carcass Jack",
  "Skyforth",
  "Tinkerskin",
  "Tinkerskin",
  "Curtain Call",
  "The Devouring Diadem",
  "Hands of the High Templar",
  "Voidfletcher",
  "Sundance",
  "Slitherpinch",
  "Dendrobate",
  "Skullhead",
  "Thousand Teeth Temu",
  "Lioneye's Vision",
  "Saffell's Frame",
  "Hale Negator",
  "Shroud of the Lightless",
  "The Deep One's Hide",
  "Bronn's Lithe",
  "Vis Mortis",
  "Daresso's Defiance",
  "The Covenant",
  "The Coming Calamity",
  "Hyrri's Ire",
  "Soul Mantle",
  "Fleshcrafter",
  "Gruthkul's Pelt",
  "Atziri's Splendour",
  "Dendrobate",
  "Belly of the Beast",
  "The Beast Fur Shawl",
  "Victario's Influence",
  "The Brass Dome",
  "Lioneye's Vision",
  "Cherrubim's Maleficence",
  "The Ivory Tower",
  "Sporeguard",
  "Cloak of Defiance",
  "Craiceann's Carapace",
  "Maloney's Mechanism",
  "The Tempest's Binding",
  "Assailum",
  "Whakatutuki o Matua",
  "Triad Grip",
  "Iron Heart",
  "Oskarm",
  "Sentari's Answer",
  "Jaws of Agony",
  "Blackgleam",
  "The Anticipation",
  "Saqawal's Flock",
  "Bitterbind Point",
  "Death's Oath",
  "Worldcarver",
  "Light of Lunaris",
  "Vixen's Entrapment",
  "Seven-League Step",
  "Malachai's Simula",
  "Atziri's Mirror",
  "Crown of Thorns",
  "Hyrri's Bite",
  "Malachai's Loop",
  "Shavronne's Pace",
  "Veil of the Night",
  "The Restless Ward",
  "Thunderfist",
  "Maligaro's Lens",
  "Doedre's Scorn",
  "Lightning Coil",
  "Crown of Eyes",
  "Doedre's Skin",
  "Lightbane Raiment",
  "Chernobog's Pillar",
  "Loreweave",
  "Prism Guardian",
  "Heretic's Veil",
  "Maligaro's Virtuosity",
  "Empire's Grasp",
  "Black Sun Crest",
  "Voidbringer",
  "The Brine Crown",
  "The Ivory Tower",
  "The Queen's Hunger",
  "The Broken Crown",
  "Yriel's Fostering",
  "Thousand Ribbons",
  "Victario's Charity",
  "Heatshiver",
  "Ondar's Clasp",
  "Perepiteia",
  "Craiceann's Chitin",
  "Perfidy",
  "Manastorm",
  "Aegis Aurora",
  "Invictus Solaris",
  "Dialla's Malefaction",
  "Icetomb",
  "Vaal Caress",
  "Loreweave",
  "March of the Legion",
  "Maw of Conquest",
  "Solaris Lorica",
  "Windscream",
  "Magna Eclipsis",
  "Rise of the Phoenix",
  "Esh's Mirror",
  "Fox's Fortune",
  "Kaltensoul",
  "Geofri's Legacy",
  "Craghead",
  "Thirst for Horrors",
  "Deidbellow",
  "Hyrri's Demise",
  "Cragfall",
  "Lioneye's Remorse",
  "Doedre's Malevolence",
  "Malachai's Mark",
  "Asenath's Gentle Touch",
  "The Bringer of Rain",
  "Eye of Malice",
  "The Red Trail",
  "Chains of Command",
  "Yriel's Fostering",
  "Foxshade",
  "Mask of the Spirit Drinker",
  "The Brass Dome",
  "Farrul's Chase",
  "Belly of the Beast",
  "Doryani's Delusion",
  "Null and Void",
  "Ahn's Heritage",
  "Fenumus' Toxins",
  "Fenumus' Shroud",
  "Allelopathy",
  "Meginord's Vise",
  "Wheel of the Stormsail",
  "Grip of the Council",
  "Saqawal's Nest",
  "Zahndethus' Cassock",
  "Cowl of the Thermophile",
  "Cowl of the Ceraunophile",
  "Unyielding Flame",
  "Vis Mortis",
  "Scorpion's Call",
  "Wake of Destruction",
  "Redblade Banner",
  "Deidbell",
  "Breathstealer",
  "Lycosidae",
  "Wall of Brambles",
  "Leper's Alms",
  "Martyr's Crown",
  "Rathpith Globe",
  "Goldrim",
  "The Formless Inferno",
  "Dendrobate",
  "Icetomb",
  "Rigwald's Quills",
  "Rotting Legion",
  "Voll's Protector",
  "The Shattered Divinity",
  "The Tempest's Liberation",
  "Obscurantis",
  "Cloak of Flame",
  "The Rat Cage",
  "The Restless Ward",
  "Doryani's Fist",
  "Winds of Change",
  "Voll's Vision",
  "Brinerot Flag",
  "Trolltimber Spire",
  "Icetomb",
  "The Snowblind Grace",
  "Indigon",
  "Chalice of Horrors",
  "Flamesight",
  "Saemus' Gift",
  "Fairgraves' Tricorne",
  "Leer Cast",
  "Galesight",
  "Kaltenhalt",
  "Ashrend",
  "Tukohama's Fortress",
  "Skin of the Loyal",
  "Inya's Epiphany",
  "The Queen's Hunger",
  "Bloodbond",
  "Dusktoe",
  "Geofri's Sanctuary",
  "Zeel's Amplifier",
  "Cloak of Defiance",
  "Perfidy",
  "Briskwrap",
  "Algor Mortis",
  "Solaris Lorica",
  "The Iron Fortress",
  "Bronn's Lithe",
  "Lightning Coil",
  "Infernal Mantle",
  "The Restless Ward",
  "Mistwall",
  "Atziri's Reflection",
  "Infernal Mantle",
  "Speaker's Wreath",
  "Kintsugi",
  "Doedre's Skin",
  "Shavronne's Wrappings",
  "Bloodbond",
  "Cloak of Tawm'r Isley",
  "The Signal Fire",
  "Repentance",
  "Zahndethus' Cassock",
  "Chains of Command",
  "Incandescent Heart",
  "Chains of Command",
  "Doedre's Skin",
  "Cherrubim's Maleficence",
  "Kingsguard",
  "The Covenant",
  "Bloodbond",
  "Fenumus' Shroud",
  "Fenumus' Weave",
  "Daresso's Courage",
  "Ashrend",
  "Queen of the Forest",
  "The Coming Calamity",
  "Mind of the Council",
  "Apep's Supremacy",
  "Springleaf",
  "Mindspiral",
  "Broken Faith",
  "Mutewind Pennant",
  "Bramblejack",
  "Inpulsa's Broken Heart",
  "The Perfect Form",
  "Greed's Embrace",
  "Omeyocan",
  "Greed's Embrace",
  "Aukuna's Will",
  "Farrul's Fur",
  "Asenath's Chant",
  "Cospri's Will",
  "Doryani's Prototype",
  "Demigod's Beacon",
  "Demigod's Dominance",
  "Crest of Perandus",
  "Garb of the Ephemeral",
  "Dialla's Malefaction",
  "Fleshcrafter",
  "Glitterdisc",
  "Ambu's Charge",
  "Farrul's Pounce",
  "Cowl of the Cryophile",
  "Crown of the Tyrant",
  "Titucius' Span",
  "Crown of the Pale King",
  "Farrul's Bite",
  "The Queen's Hunger",
  "Saqawal's Nest",
  "Shadowstitch",
  "The Rat Cage",
  "Garb of the Ephemeral",
  "Mask of the Stitched Demon",
  "Malachai's Vision",
  "Dialla's Malefaction",
  "Cloak of Flame",
  "Ahn's Contempt",
  "Apep's Slumber",
  "Fox's Fortune",
  "Wall of Brambles",
  "Atziri's Splendour",
  "Chitus' Apex",
  "Hrimburn",
  "Death's Oath",
  "The Perfect Form",
  "Greed's Embrace",
  "Thousand Ribbons",
  "Victario's Influence",
  "Kitava's Thirst",
  "Foxshade",
  "Lightning Coil",
  "The Beast Fur Shawl",
  "Malachai's Awakening",
  "Foxshade",
  "Ambu's Charge",
  "Craiceann's Carapace",
  "Briskwrap",
  "Daresso's Defiance",
  "Death's Door",
  "Demigod's Triumph",
  "Rearguard",
  "Architect's Hand",
  "Garukhan's Flight",
  "Fox's Fortune",
  "The Perfect Form",
  "Ezomyte Hold",
  "Machina Mitts",
  "Rotting Legion",
  "Death's Oath",
  "Kintsugi",
  "Rotting Legion",
  "Ylfeban's Trickery",
  "Bramblejack",
  "Perfidy",
  "The Iron Fortress",
  "Wildwrap",
  "Deshret's Vise",
  "Wall of Brambles",
  "Crystal Vault",
  "The Oak",
  "Voll's Protector",
  "Iron Heart",
  "The Eternity Shroud",
  "Plume of Pursuit",
  "Viper's Scales",
  "Slavedriver's Hand",
  "Solaris Lorica",
  "Broadstroke",
  "The Iron Fortress",
  "Lightbane Raiment",
  "Ashrend",
  "Iron Heart",
  "Gruthkul's Pelt",
  "Garb of the Ephemeral",
  "Doryani's Prototype",
  "Briskwrap",
  "Forbidden Shako",
  "Abhorrent Interrogation",
  "The Immortal Will",
  "Willclash",
  "The Ghastly Theatre",
  "Mercenary's Lot",
  "Crest of Desire",
  "Blunderbore",
  "Expedition's End",
  "Replica Grip of the Council",
  "Replica Perfect Form",
  "Replica Alberon's Warpath",
  "Replica Inya's Epiphany",
  "Replica Eternity Shroud",
  "Replica Atziri's Acuity",
  "Replica Red Trail",
  "Replica Maloney's Mechanism",
  "Replica Ambu's Charge",
  "Replica Voidwalker",
  "Replica Kaom's Heart",
  "Replica Mistwall",
  "Replica Bones of Ullr",
  "Replica Farrul's Fur",
  "Replica Shroud of the Lightless",
  "Maw of Mischief",
  "The Fledgling",
  "Corpsewalker",
];

/* 

Go through each object and iterate the object on chrome console to grab all array entries

*/

export const currency = [
  {
      "id": "alt",
      "text": "Orb of Alteration",
      "image": "/image/Art/2DItems/Currency/CurrencyRerollMagic.png?v=6d9520174f6643e502da336e76b730d3"
  },
  {
      "id": "fusing",
      "text": "Orb of Fusing",
      "image": "/image/Art/2DItems/Currency/CurrencyRerollSocketLinks.png?v=0ad7134a62e5c45e4f8bc8a44b95540f"
  },
  {
      "id": "alch",
      "text": "Orb of Alchemy",
      "image": "/image/Art/2DItems/Currency/CurrencyUpgradeToRare.png?v=89c110be97333995522c7b2c29cae728"
  },
  {
      "id": "chaos",
      "text": "Chaos Orb",
      "image": "/image/Art/2DItems/Currency/CurrencyRerollRare.png?v=c60aa876dd6bab31174df91b1da1b4f9"
  },
  {
      "id": "gcp",
      "text": "Gemcutter's Prism",
      "image": "/image/Art/2DItems/Currency/CurrencyGemQuality.png?v=f11792b6dbd2f5f869351151bc3a4539"
  },
  {
      "id": "exalted",
      "text": "Exalted Orb",
      "image": "/image/Art/2DItems/Currency/CurrencyAddModToRare.png?v=1745ebafbd533b6f91bccf588ab5efc5"
  },
  {
      "id": "chrome",
      "text": "Chromatic Orb",
      "image": "/image/Art/2DItems/Currency/CurrencyRerollSocketColours.png?v=9d377f2cf04a16a39aac7b14abc9d7c3"
  },
  {
      "id": "jewellers",
      "text": "Jeweller's Orb",
      "image": "/image/Art/2DItems/Currency/CurrencyRerollSocketNumbers.png?v=2946b0825af70f796b8f15051d75164d"
  },
  {
      "id": "engineers",
      "text": "Engineer's Orb",
      "image": "/image/Art/2DItems/Currency/EngineersOrb.png?v=4b291fd7d6b9022a2d35b34c43c08e87"
  },
  {
      "id": "infused-engineers-orb",
      "text": "Infused Engineer's Orb",
      "image": "/image/Art/2DItems/Currency/InfusedEngineersOrb.png?v=450cbf4248c1b129b52da9cbef5439cc"
  },
  {
      "id": "chance",
      "text": "Orb of Chance",
      "image": "/image/Art/2DItems/Currency/CurrencyUpgradeRandomly.png?v=e4049939b9cd61291562f94364ee0f00"
  },
  {
      "id": "chisel",
      "text": "Cartographer's Chisel",
      "image": "/image/Art/2DItems/Currency/CurrencyMapQuality.png?v=f46e0a1af7223e2d4cae52bc3f9f7a1f"
  },
  {
      "id": "scour",
      "text": "Orb of Scouring",
      "image": "/image/Art/2DItems/Currency/CurrencyConvertToNormal.png?v=15e3ef97f04a39ae284359309697ef7d"
  },
  {
      "id": "blessed",
      "text": "Blessed Orb",
      "image": "/image/Art/2DItems/Currency/CurrencyImplicitMod.png?v=472eeef04846d8a25d65b3d4f9ceecc8"
  },
  {
      "id": "regret",
      "text": "Orb of Regret",
      "image": "/image/Art/2DItems/Currency/CurrencyPassiveSkillRefund.png?v=1de687952ce56385b74ac450f97fcc33"
  },
  {
      "id": "regal",
      "text": "Regal Orb",
      "image": "/image/Art/2DItems/Currency/CurrencyUpgradeMagicToRare.png?v=1187a8511b47b35815bd75698de1fa2a"
  },
  {
      "id": "divine",
      "text": "Divine Orb",
      "image": "/image/Art/2DItems/Currency/CurrencyModValues.png?v=0ad99d4a2b0356a60fa8194910d80f6b"
  },
  {
      "id": "vaal",
      "text": "Vaal Orb",
      "image": "/image/Art/2DItems/Currency/CurrencyVaal.png?v=64114709d67069cd665f8f1a918cd12a"
  },
  {
      "id": "annul",
      "text": "Orb of Annulment",
      "image": "/image/Art/2DItems/Currency/AnnullOrb.png?v=f9a0f8b21515c8abf517e9648cfc7455"
  },
  {
      "id": "orb-of-binding",
      "text": "Orb of Binding",
      "image": "/image/Art/2DItems/Currency/BindingOrb.png?v=6ee0528156592a01c2931262d024f842"
  },
  {
      "id": "ancient-orb",
      "text": "Ancient Orb",
      "image": "/image/Art/2DItems/Currency/AncientOrb.png?v=3edb14b53b9b05e176124814aba86f94"
  },
  {
      "id": "orb-of-horizons",
      "text": "Orb of Horizons",
      "image": "/image/Art/2DItems/Currency/HorizonOrb.png?v=f3b3343dc61c60e667003bbdbbdb2374"
  },
  {
      "id": "harbingers-orb",
      "text": "Harbinger's Orb",
      "image": "/image/Art/2DItems/Currency/HarbingerOrb.png?v=a61bf3add692a2fe74bb5f39213f4d93"
  },
  {
      "id": "wisdom",
      "text": "Scroll of Wisdom",
      "image": "/image/Art/2DItems/Currency/CurrencyIdentification.png?v=1b9b38c45be95c59d8900f91b2afd58b"
  },
  {
      "id": "portal",
      "text": "Portal Scroll",
      "image": "/image/Art/2DItems/Currency/CurrencyPortal.png?v=728696ea10d4fb1e789039debc5d8c3c"
  },
  {
      "id": "scrap",
      "text": "Armourer's Scrap",
      "image": "/image/Art/2DItems/Currency/CurrencyArmourQuality.png?v=251e204e4ec325f75ce8ef75b2dfbeb8"
  },
  {
      "id": "whetstone",
      "text": "Blacksmith's Whetstone",
      "image": "/image/Art/2DItems/Currency/CurrencyWeaponQuality.png?v=d2ce9167e23a74cef5d8465433e86482"
  },
  {
      "id": "bauble",
      "text": "Glassblower's Bauble",
      "image": "/image/Art/2DItems/Currency/CurrencyFlaskQuality.png?v=ca8bd0dd43d2adf8b021578a398eb9de"
  },
  {
      "id": "transmute",
      "text": "Orb of Transmutation",
      "image": "/image/Art/2DItems/Currency/CurrencyUpgradeToMagic.png?v=333b8b5e28b73c62972fc66e7634c5c8"
  },
  {
      "id": "aug",
      "text": "Orb of Augmentation",
      "image": "/image/Art/2DItems/Currency/CurrencyAddModToMagic.png?v=97e63b85807f2419f4208482fd0b4859"
  },
  {
      "id": "mirror",
      "text": "Mirror of Kalandra",
      "image": "/image/Art/2DItems/Currency/CurrencyDuplicate.png?v=6fd68c1a5c4292c05b97770e83aa22bc"
  },
  {
      "id": "eternal",
      "text": "Eternal Orb",
      "image": "/image/Art/2DItems/Currency/CurrencyImprintOrb.png?v=0483ded9ac1f08c320fc21d5ddc208c0"
  },
  {
      "id": "p",
      "text": "Perandus Coin",
      "image": "/image/Art/2DItems/Currency/CurrencyCoin.png?v=b971d7d9ea1ad32f16cce8ee99c897cf"
  },
  {
      "id": "silver",
      "text": "Silver Coin",
      "image": "/image/Art/2DItems/Currency/SilverObol.png?v=93c1b204ec2736a2fe5aabbb99510bcf"
  },
  {
      "id": "crusaders-exalted-orb",
      "text": "Crusader's Exalted Orb",
      "image": "/image/Art/2DItems/Currency/Influence%20Exalts/CrusaderOrb.png?v=966e5b961c6dd6f6f1a1f927e90ea0b8"
  },
  {
      "id": "redeemers-exalted-orb",
      "text": "Redeemer's Exalted Orb",
      "image": "/image/Art/2DItems/Currency/Influence%20Exalts/EyrieOrb.png?v=0fde1a481d021853ca7866254839b09a"
  },
  {
      "id": "hunters-exalted-orb",
      "text": "Hunter's Exalted Orb",
      "image": "/image/Art/2DItems/Currency/Influence%20Exalts/BasiliskOrb.png?v=1ae3d1331ddf5a97aeb520f21564965e"
  },
  {
      "id": "warlords-exalted-orb",
      "text": "Warlord's Exalted Orb",
      "image": "/image/Art/2DItems/Currency/Influence%20Exalts/ConquerorOrb.png?v=4a2db92846fa5bbb9e7607a8db854ab4"
  },
  {
      "id": "awakeners-orb",
      "text": "Awakener's Orb",
      "image": "/image/Art/2DItems/Currency/TransferOrb.png?v=1afda4f097beb4ba91fa111934c2572d"
  },
  {
      "id": "facetors",
      "text": "Facetor's Lens",
      "image": "/image/Art/2DItems/Currency/CurrencyGemExperience.png?v=3d005916b44ac5cc03714d71e4d20146"
  },
  {
      "id": "rogues-marker",
      "text": "Rogue's Marker",
      "image": "/image/Art/2DItems/Currency/Heist/HeistCoinCurrency.png?v=91f470e219855da2a828fd553feb30f6"
  },
  {
      "id": "prime-regrading-lens",
      "text": "Prime Regrading Lens",
      "image": "/image/Art/2DItems/Currency/AlternateSkillGemCurrency.png?v=634a6af3d5429427461933d11843fa45"
  },
  {
      "id": "secondary-regrading-lens",
      "text": "Secondary Regrading Lens",
      "image": "/image/Art/2DItems/Currency/AlternateSupportGemCurrency.png?v=f542ce9b30b707538c3673b82d6f57af"
  },
  {
      "id": "tempering-orb",
      "text": "Tempering Orb",
      "image": "/image/Art/2DItems/Currency/DivineEnchantBodyArmourCurrency.png?v=d072c438605f9e018a771d631a09d126"
  },
  {
      "id": "tailoring-orb",
      "text": "Tailoring Orb",
      "image": "/image/Art/2DItems/Currency/DivineEnchantWeaponCurrency.png?v=a04c73695d57792be93cbf91864a2467"
  },
  {
      "id": "annulment-shard",
      "text": "Annulment Shard",
      "image": "/image/Art/2DItems/Currency/AnnullShard.png?v=502496c41d3da750bcecbb194d0aa3f4"
  },
  {
      "id": "mirror-shard",
      "text": "Mirror Shard",
      "image": "/image/Art/2DItems/Currency/MirrorShard.png?v=b5b677eece4ae7e8450452e3944f121d"
  },
  {
      "id": "exalted-shard",
      "text": "Exalted Shard",
      "image": "/image/Art/2DItems/Currency/ExaltedShard.png?v=4945fe24b79868be79870f8ad01f20b0"
  },
  {
      "id": "binding-shard",
      "text": "Binding Shard",
      "image": "/image/Art/2DItems/Currency/BindingShard.png?v=b00f27dee8ad94d7f187133a09b872f9"
  },
  {
      "id": "horizon-shard",
      "text": "Horizon Shard",
      "image": "/image/Art/2DItems/Currency/HorizonShard.png?v=6d0e5b4c1bbaeb06c8cd10c269ad8121"
  },
  {
      "id": "harbingers-shard",
      "text": "Harbinger's Shard",
      "image": "/image/Art/2DItems/Currency/HarbingerShard.png?v=2274561da4960ca41bb6742952edc74d"
  },
  {
      "id": "engineers-shard",
      "text": "Engineer's Shard",
      "image": "/image/Art/2DItems/Currency/EngineersShard.png?v=8b69b76b1f42120f72cf7febb76b6a7a"
  },
  {
      "id": "ancient-shard",
      "text": "Ancient Shard",
      "image": "/image/Art/2DItems/Currency/AncientShard.png?v=e1eb08f64822576bd6d47029cd72d1a9"
  },
  {
      "id": "chaos-shard",
      "text": "Chaos Shard",
      "image": "/image/Art/2DItems/Currency/ChaosShard.png?v=c206269aeda3a6a7b5a8ac110045afca"
  },
  {
      "id": "regal-shard",
      "text": "Regal Shard",
      "image": "/image/Art/2DItems/Currency/RegalShard.png?v=e10a1590d421e4305d8a19ff8c4d9948"
  },
  {
      "id": "apprentice-sextant",
      "text": "Simple Sextant",
      "image": "/image/Art/2DItems/Currency/AtlasRadiusTier1.png?v=7c21fc06120d910018893083227406df"
  },
  {
      "id": "journeyman-sextant",
      "text": "Prime Sextant",
      "image": "/image/Art/2DItems/Currency/AtlasRadiusTier2.png?v=043e5f4d8c52af6b302e30afaffa5eba"
  },
  {
      "id": "master-sextant",
      "text": "Awakened Sextant",
      "image": "/image/Art/2DItems/Currency/AtlasRadiusTier3.png?v=d69377f526ff51c408461b0cee4d4ade"
  },
  {
      "id": "blessing-xoph",
      "text": "Blessing of Xoph",
      "image": "/image/Art/2DItems/Currency/Breach/BreachUpgraderFire.png?v=6c7efd3a8fc9150d4b293d5a5917fd04"
  },
  {
      "id": "blessing-tul",
      "text": "Blessing of Tul",
      "image": "/image/Art/2DItems/Currency/Breach/BreachUpgraderCold.png?v=c25b6df9be1fd051d99616e4bb78066e"
  },
  {
      "id": "blessing-esh",
      "text": "Blessing of Esh",
      "image": "/image/Art/2DItems/Currency/Breach/BreachUpgraderLightning.png?v=ed7bb0e73f5ca907ef62592e48d442dc"
  },
  {
      "id": "blessing-uul-netol",
      "text": "Blessing of Uul-Netol",
      "image": "/image/Art/2DItems/Currency/Breach/BreachUpgraderPhysical.png?v=cf3d245db6b6bb796112a952d74543e0"
  },
  {
      "id": "blessing-chayula",
      "text": "Blessing of Chayula",
      "image": "/image/Art/2DItems/Currency/Breach/BreachUpgraderChaos.png?v=841360bbd5f81619761a0d16f8c36793"
  },
  {
      "id": "splinter-xoph",
      "text": "Splinter of Xoph",
      "image": "/image/Art/2DItems/Currency/Breach/BreachShardFire.png?v=4635e0847323cf1d62c8b4e8101351bf"
  },
  {
      "id": "splinter-tul",
      "text": "Splinter of Tul",
      "image": "/image/Art/2DItems/Currency/Breach/BreachShardCold.png?v=4a7652d6ff5de2493d37768e993c9411"
  },
  {
      "id": "splinter-esh",
      "text": "Splinter of Esh",
      "image": "/image/Art/2DItems/Currency/Breach/BreachShardLightning.png?v=11cd23560f7aa0dda27cc323fa97cb96"
  },
  {
      "id": "splinter-uul",
      "text": "Splinter of Uul-Netol",
      "image": "/image/Art/2DItems/Currency/Breach/BreachShardPhysical.png?v=25f31f4a5e1ba4540cb7bfa03b82c1e8"
  },
  {
      "id": "splinter-chayula",
      "text": "Splinter of Chayula",
      "image": "/image/Art/2DItems/Currency/Breach/BreachShardChaos.png?v=2c18cbe5384375bbe4643cd8b83ea32d"
  },
  {
      "id": "timeless-karui-splinter",
      "text": "Timeless Karui Splinter",
      "image": "/image/Art/2DItems/Maps/KaruiShard.png?v=e3ab494b7e170292856cd88874110b61"
  },
  {
      "id": "timeless-maraketh-splinter",
      "text": "Timeless Maraketh Splinter",
      "image": "/image/Art/2DItems/Maps/MarakethShard.png?v=e0b5a2a9dd104c9884025da7191cdb9e"
  },
  {
      "id": "timeless-eternal-empire-splinter",
      "text": "Timeless Eternal Empire Splinter",
      "image": "/image/Art/2DItems/Maps/EternalEmpireShard.png?v=c39753adba56300b8c08f3066a79429c"
  },
  {
      "id": "timeless-templar-splinter",
      "text": "Timeless Templar Splinter",
      "image": "/image/Art/2DItems/Maps/TemplarShard.png?v=82d3d517ed1caa15a3dfad5f3a0a8fff"
  },
  {
      "id": "timeless-vaal-splinter",
      "text": "Timeless Vaal Splinter",
      "image": "/image/Art/2DItems/Maps/VaalShard.png?v=0a4bddb57e7c348f72bfffd3434f0e6b"
  },
  {
      "id": "simulacrum-splinter",
      "text": "Simulacrum Splinter",
      "image": "/image/Art/2DItems/Maps/DeliriumSplinter.png?v=63d53dfdcf5b047248b781187d66624b"
  },
  {
      "id": "stacked-deck",
      "text": "Stacked Deck",
      "image": "/image/Art/2DItems/Divination/Deck.png?v=0e5e6da39f79fc57f3d38d463126617a"
  }
]

export const result = [
  {
    label: "Accessories",
    entries: removeDuplicates(accessories),
  },
  {
    label: "Armours",
    entries: removeDuplicates(armours),
  },
];

function removeDuplicates(array) {
  return [...new Set(array)];
}

// LARGE STACK
export const stack = removeDuplicates(accessories.concat(armours));

